package com.prakpapb2.utils;

public class DataPahlawanEn {

    static final int[] id = {
            1,
            2,
            3,
            4,
            5
    };

    static final String[] photoPahlawan = {
            "https://cdn1-production-images-kly.akamaized.net/SoUvACur9TC9Kf5P_T4zLIV-DsQ=/640x853/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/1238080/original/005070900_1463635462-dr_Soetomo_-_dr_Sutomo.jpg",
            "https://scontent.fcgk30-1.fna.fbcdn.net/v/t31.18172-8/23592385_507734569596894_1225625643885781021_o.jpg?_nc_cat=104&ccb=1-3&_nc_sid=973b4a&_nc_ohc=gFfPmtrifrcAX-8Y9xf&_nc_ht=scontent.fcgk30-1.fna&oh=362ad54a42b6519e3772df82abbea259&oe=60D178A4",
            "https://3.bp.blogspot.com/-0b8OK4m2K0k/WIAa-cBDUBI/AAAAAAAAREA/Qt-faNv9tpsbixCBOaI-h5ISFgDhKHGiACLcB/w600/Tokoh%2BPeletak%2BDasar%2BPendidikan%2BNasional.jpg",
            "https://www.matakota.id/uploads/images/news/1501765097362.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Portret_van_de_schrijver_Multatuli_%28cropped%29.jpg/330px-Portret_van_de_schrijver_Multatuli_%28cropped%29.jpg",
            "http://3.bp.blogspot.com/-3CQivNjiJqo/TWJXeHI6BfI/AAAAAAAAAV8/1RbC_JMNXtU/s320/cut-nyak-dhien.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cut_Nyak_Meutia.jpg/263px-Cut_Nyak_Meutia.jpg",
            "https://www.inhilklik.com/assets/berita/original/83162943273-63828780781-20200218_153258.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/5/53/Sri_Susuhunan_Pakubuwono_VI.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sudirman.jpg/729px-Sudirman.jpg",
            "https://files.kajanglako.com/images/uploads/kj-gambar-20200411_o701VS.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg",
            "https://kebudayaan.kemdikbud.go.id/muspres/wp-content/uploads/sites/38/2020/02/images.jpg",
            "https://cdn.idntimes.com/content-images/community/2020/05/dewi-sartika-92820ae8f02b5cfd1ff77967b3f9e760.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/MT_Haryono.jpg/330px-MT_Haryono.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Ahmad_Yani.jpg/300px-Ahmad_Yani.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/S_Parman.jpg/330px-S_Parman.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Soeprapto.jpg/330px-Soeprapto.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Panjaitan.jpg/330px-Panjaitan.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Sutoyo.jpg/330px-Sutoyo.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/e/ec/Tendean.jpg",
            ""

    };

    static final String[] namaPahlawan = {
            "dr.Soetomo",
            "Ir.Soekarno (EN)",
            "Ki Hajar Dewantara",
            "dr.Cipto Mangunkusumo",
            "Douwes Dekker",
            "Cut Nyak Dhien",
            "Cut Meutia",
            "Sisingamangaraja XII",
            "Pakubowono",
            "Jenderal Soedirman",
            "Sutan Sjahrir",
            "R.A. Kartini",
            "Fatmawati",
            "Raden Dewi Sartika",
            "Cut Meutia",
            "Mayjen MT Haryono",
            "Jenderal Ahmad Yani",
            "Mayjen S.Parman",
            "Mayjen R.Suprapto",
            "Brigjen D.I Panjaitan",
            "Brigjen Sutoyo",
            "Lettu Pierre Tandean"
    };

    static final String[] deskripsiPahlawan = {
            "Doctor Soetomo whose real name is Soebroto, was born in Ngepeh, East Java, July 30, 1888 and died in Surabaya, May 30, 1938 and was buried in Surabaya. He is the founding figure of Budi Utomo as well as a Hero of National Independence based on the Decree of the President of the Republic of Indonesia No. 657 of 1961, dated December 27, 1961\n" +
                    "\n" +
                    "Dr.Sutomo studied medical school at STOVIA and often held discussions with his colleagues. On the advice of dr. Wahidin Soedirohoesodo, Soetomo founded Boedi Oetomo on May 20, 1908. Boedi Oetomo was the first modern organization born in Indonesia and Soetomo was appointed as its chairman. This organization aims to promote education and culture as a way to free the nation from colonialism.\n" +
                    "\n" +
                    "In 1911 Soetomo graduated from STOVIA and then got an assignment in Semarang. From there he was transferred to Tuban, then to Lubuk Pakam (North Sumatra) and finally to Malang. In the city of Malang he had to eradicate the bubonic plague that was engulfing the area.\n" +
                    "\n" +
                    "Due to the frequent shifts of work places, Soetomo gained a lot of experience. He is increasingly aware of the plight of the people and can directly help them. As a doctor He helps without expecting anything in return from his patients, sometimes patients are exempt from payment.\n" +
                    "\n" +
                    "In 1919, Soetomo had the opportunity to deepen his knowledge in the Netherlands. his busy studies did not extinguish his interest in politics. In the Netherlands he joined the Indonesian Association. Upon his return to Indonesia, he saw that there was a weakness in Boedi Oetomo. In Indonesia at that time, there were already many parties. He suggested that Boedi Oetomo be engaged in politics and that its membership is open to all members of the community.\n" +
                    "\n" +
                    "In 1924, Soetomo founded the Indonesische Studie Club (ISC) which was a forum for the educated. ISC succeeded in establishing student dormitories, weaving schools, credit banks, cooperatives and so on.\n" +
                    "\n" +
                    "In 1931, the ISC changed its name to the United Nations of Indonesia (PBI). Under the leadership of Soetomo, PBI developed rapidly. Due to increasingly harsh pressure from the Dutch government, in 1935 Boedi Oetomo and PBI were merged into one under the name of the Great Indonesia Party (Parindra), which struggled to achieve an independent Indonesia.\n" +
                    "\n" +
                    "Doctor Soetomo is also active in journalism and even leads several newspapers. His busyness and struggle made his health weak. He died in Surabaya on May 30, 1938. To honor his services, dr. Soetomo was appointed as a Hero of National Independence based on the Decree of the President of the Republic of Indonesia No. 657/1961.",
            "Ir. Soekarno was the first president of the Republic of Indonesia, as well as the proclaimed figure of the Republic of Indonesia. \n"+
                    "\n" +
                    "Bung Karno was born in Surabaya, June 6, 1901 and died in Jakarta, June 21, 1970. On August 17, 1945, Indonesia declared its independence. On August 18, 1945, Sukarno and Mohammad Hatta were appointed by PPKI to become President and Vice President of the Republic of Indonesia. On August 29, 1945 the appointment of President Soekarno and Vice President Mohammad Hatta was confirmed by the KNIP.",
            "Raden Mas Soewardi Soerjaningrat, since 1922 as Ki Hadjar Dewantara, several Javanese to write the voice of Ki Hajar Dewantoro, born in Yogyakarta, 2 May 1889 and died in Yogyakarta, 26 April 1959 at the age of 69, is an Indonesian independence movement activist, columnist, politician , and a pioneer in education for indigenous Indonesians from the Dutch colonial era.\n" +
                    "\n" +
                    "He is the founder of the Taman Siswa College, an educational institution that provides opportunities for indigenous commoners to be able to obtain the right to education as well as the aristocracy and the Netherlands.\n" +
                    "\n" +
                    "The date of birth is now celebrated in Indonesia as National Education Day. Part of the creation of the slogan, tut wuri handayani, became the slogan of the Indonesian Ministry of National Education. His name is immortalized as one of the names of the Indonesian warship KRI Ki Hajar Dewantara. His image is immortalized on the 1998 $20,000 emission bill.\n" +
                    "\n" +
                    "He was inaugurated as the 2nd national hero by the President, Soekarno, on November 28, 1959 (Presidential Decree of the Republic of Indonesia Number 305 of 1959, dated November 28, 1959).\n" +
                    "\n" +
                    "His teaching experience was used to develop teaching concepts for the school he founded on 3 July 1922: National Onderwijs Instituut Tamansiswa or Tamansiswa National University.\n" +
                    "\n" +
                    "When he reached the age of 40 according to the Javanese calendar, he changed his name to Ki Hadjar Dewantara. He no longer used a peerage in front of his name. This means that he can freely be close to the people, both physically and mentally.\n" +
                    "\n" +
                    "The motto in the education system that is currently used is very well known among education circles in Indonesia. Overall, the slogan reads in Javanese sung by Tulodo ngarso ing, ing Madyo Mangun Karso, tut wuri handayani. \"In front of giving an example, in the middle giving encouragement, giving encouragement back\". This slogan is still used in the education of the Indonesian people, especially in Tamansiswa schools.",
            "Tjipto Mangoenkoesoemo is known as one of the leaders of the Indonesian independence movement who is also dubbed as a member of the Tiga Serangkai with Ernest Douwes Dekker and Ki Hajar Dewantara. In addition to devoting his life as a doctor, Tjipto is also engaged in politics to oppose Dutch colonialism. When his two colleagues in Tiga Serangkai changed direction to move in the field of education, he remained faithful to the political path until the end of his life.\n" +
                    "\n" +
                    "Tjipto did not come from a priyayi family who had a high social position. However, because of his intelligence, he was able to attend STOVIA or the Indian Medical Education School. His dissatisfaction with the regulations in STOVIA as well as his concern for the condition of the Indonesian people under the Dutch colonial rule at that time made him active in expressing all his thoughts and criticisms in the daily De Locomotief since 1907. He also spread his views which were full of political values \u200B\u200Bby joined the Budi Utomo organization. But in the end he decided to resign from Budi Utomo because of the ideological divisions within the organization which was formed on May 20, 1908. He then founded Indische Partij with Ernest Douwes Dekker and Ki Hajar Dewantara on December 25, 1912. At that time Indische Partij was the only organization that was openly engaged in politics and aimed at achieving an independent Indonesia. In 1913, the three founders of the Indische Partij were arrested and exiled to the Netherlands because of the anti-Dutch propaganda they put into an article in the daily De Express containing their opposition to the celebration of Dutch independence in Indonesia. Their presence in the Netherlands had an important influence on the Indische Vereeniging, the Indonesian student association in the Netherlands, in supporting the independence movement.\n" +
                    "\n" +
                    "Due to illness, Tjipto was sent back to Java in 1914. After his return, he joined Insulinde, an association that replaced the Indische Partij which later changed its name to the National Indische Partij (NIP). In 1918, he became a member of the Dutch Volksraad (People's Council). He used the Volksraad as a place to express his aspirations and criticize the government on social and political issues. Because it was considered dangerous, the Dutch East Indies government expelled Tjipto to Bandung. There he met Soekarno. Tjipto was also expelled for the umpteenth time in 1928 because he was accused of taking part in a communist rebellion. He was exiled to the island of Banda but was eventually returned to the island of Java due to his deteriorating health condition.",
            "Eduard Douwes Dekker, later known as Multatuli, was born on March 2, 1820 in Amsterdam, the Netherlands. He comes from a simple family. His father was a skipper named Engel Douweszoon Dekker while his mother was named Sytske Eeltje Klein. He is the fourth child.\n" +
                    "\n" +
                    "At the age of 18 he went to the Dutch East Indies to try his luck. In 1839 he became a civil servant in the Dutch East Indies. In 1842 he was transferred to West Sumatra and became controller at Natal. But then he was transferred to Padang because he could not account for the contents of the cash he held. Since then he is familiar with poverty.\n" +
                    "\n" +
                    "In Semtember 1845 he served successively in Karawang, Bagelen, and Manado. He met Tine, his future wife in Parakan Salak. After being engaged on August 18, 1845, they married on April 10, 1846.\n" +
                    "\n" +
                    "Eduard was appointed a commissioner at the resident's office in Purworejo a month after getting married. In October 1848 he became secretary in Manado. Then he was appointed assistant resident in Ambon in 1851. Because he was too tired he fell ill. So in 1852 he went on vacation to the Netherlands with his wife.\n" +
                    "\n" +
                    "In 1855 he returned to Batavia after his life in the Netherlands was destroyed due to his sloppy life which made his debts pile up. He and his family live in Bogor and receive a waiting fee. He was finally able to get in touch with Duymaer van Twist, the governor-general who appointed him assistant resident in Lebak and based in Rangkasbitung.\n" +
                    "\n" +
                    "On 24 February 1856 he sent a report to the Resident of Brest in Serang. He accused the regent of Lebak of abusing his power and was suspected of extortion. Two days after receiving the report, Resident Brest van Kempen immediately went to Lebak to discuss the matter.\n" +
                    "\n" +
                    "Kempen asked Douwes Dekker to hand over the archives and evidence to him. But Dekker refused, he wanted to take all the responsibility himself. In the end, the campaign immediately reported to the governor-general of Twist and demanded that Dekker be fired for disobedience. The governor general did not fire him, only transferred him to Ngawi. Douwes Dekker refused the transfer and he asked to stop. On April 20, 1856 he left Lebak and returned to the Netherlands, while his wife and children were left in Batavia.\n" +
                    "\n" +
                    "In January 1858 he arrived in Brussels, Belgium. In the inn room of Au Prince Belge, for a month in the autumn of 1859 he wrote the book Max Havelaar. It turned out that the book did not please the Dutch authorities because it contained criticism of the bad treatment of the colonialists against the indigenous people in the Dutch East Indies, and persuaded Dekker not to publish the manuscript. Dekker is willing as long as he is appointed as a resident in Pasuruan. In addition, he asked for a big dowry to pay off his debts and finally he asked for the Dutch Lion Knight Star. After bargaining, he also wanted to be appointed a member of the Council of the Dutch East Indies.\n" +
                    "\n" +
                    "The request was rejected, so Max Havelaar's book was published using the pen name Multatuli, which means I Am Suffering. It turns out that Max Havelaar is selling well. But Dekker himself continued to live in poverty and his health declined. Previously Dekker wrote many other books, but it was Max Havelaar who made his name famous. On February 19, 1887, two weeks before his birthday he died on the banks of the Rhine, Germany.",
            "Cut Nyak Dhien is an Indonesian female national hero from Aceh. She comes from a religious noble family in Aceh Besar. When she was 12 years old, Cut Nyak Dhien was married to Teuku Cek Ibrahim Lamnga who also comes from a noble family.\n" +
                    "\n" +
                    "The Dutch attacked Aceh for the first time on March 26, 1873, the enthusiasm of Cut Nyak Dhien to fight the Dutch colonial forces began. The incident of the death of Teuku Cek Ibrahim Lamnga in the war against the Dutch on June 29, 1878 further ignited the spirit and hatred of this brave woman against the invaders. He married later again with Teuku Umar who was also a national hero of Indonesia in 1880.\n" +
                    "Initially Cut Nyak Dhien refused Teuku Umar's proposal, but finally agreed to marry a man who still has a kinship line with him after Teuku Umar agreed to his desire to go down to the battlefield. He really wanted to get rid of the Dutch from Aceh and avenge his death her former husband.\n" +
                    "\n" +
                    "Together with Teuku Umar and other Acehnese fighters, Cut Nyak Dhien also aggressively attacked the Dutch. During this struggle, Cut Nyak Dhien had received insults from Cut Meutia who was also a female fighter from Aceh because of the decision of her husband, Teuku Umar, himself. the Dutch and cooperated with them. Even though Teuku Umar did not really surrender to the Dutch. This was done as a tactic to get Dutch war equipment. After his intention was carried out and he returned to Cut Nyak Dhien and his followers, the Dutch felt they had been betrayed by Teuku Umar a large-scale operation for the husband and wife pair. Teuku Umar finally died in the battle in Meulaboh on February 11, 1899.\n" +
                    "\n" +
                    "After the death of her husband, Cut Nyak Dhien was still with the Dutch. However, the gout he suffered and his near-sighted eye condition made the guards feel shocked and finally made an agreement with the Dutch that Cut Nyak Dhien could be caught properly, not as a war.\n" +
                    "\n" +
                    "After the Dutch agreed to this agreement, Cut Nyak Dhien was finally arrested and taken to Banda Aceh. He was then exiled to Sumedang on December 11, 1905 and breathed his last there on November 6, 1908. Cut Nyak Dhien's body was then interred in Mount Quail, Sumedang . ",
            "Cut Meutia is one of the female fighters from Aceh who has been recognized as an Indonesian national hero. Similar to other fighters from Tanah Rencong such as Tjoet Njak Dhien, Teuku Umar, Teuku Cik Di Tiro, and other Acehnese warrior figures, Cut Meutia is known as a brave figure and has a high fighting spirit and strong determination to get rid of the invaders.\n" +
                    "\n" +
                    "Cut Meutia fought against the Dutch with her husband Teuku Muhammad or better known as Teuku Tjik Tunong. Together they went through a long struggle, but in the end Teuku Tjik Tunong was arrested by the Dutch in March 1905. Teuku Tjik Tunong was then sentenced to death by the Dutch on the shores of Lhokseumawe. Before he died, he advised his friend Pang Nagroe to marry his wife and take care of his child after he died.\n" +
                    "\n" +
                    "According to the message of her late husband, Cut Meutia married Pang Nagroe and then joined the troops led by Teuku Muda Gantoe. In a battle against the Marechausée Corps at Paya Cicem, Pang Nagroe died in battle on 26 September 1910 while Cut Meutia survived. He and the other women who survived then fled into the forest.\n" +
                    "\n" +
                    "After the death of Pang Nagroe, Cut Meutia still continued to fight against the Dutch with a small army of his followers. They tried to attack and seize colonial outposts along their way to Gayo through the jungle. However, in the battle in Alue Kurieng on October 24, 1910, Cut Meutia was finally killed by the Dutch army's bullets. For his services, the government awarded the title of National Hero to Cut Meutia in 1964.",
            "Sisingamangaraja XII (born in Bakara, February 18, 1845 - died in Dairi, June 17, 1907 at the age of 62 years) was a king in the land of Toba, North Sumatra, a fighter who fought against the Dutch, then appointed by the Indonesian government as a National Hero of Indonesia since November 9, 1961 based on the Decree of the President of the Republic of Indonesia No. 590/1961. Previously he was buried in Tarutung Tapanuli Utara, then moved to Soposurung, Balige in 1953.\n" +
                    "\n" +
                    "Sisingamangaraja XII his first name was Patuan Bosar, which was later dubbed Ompu Pulo Batu. He is also known as Patuan Bosar Ompu Pulo Batu, ascended the throne in 1876 to replace his father Sisingamangaraja XI named Ompu Sohahuaon, besides that he is also known as the king of priests. The coronation of Sisingamangaraja XII as maharaja in the land of Toba coincided with the start of the open door policy (politics). open door) the Netherlands in securing foreign capital operating in the Dutch East Indies, and who did not want to sign the Korte Verklaring (short agreement) in Sumatra, especially the Sultanate of Aceh and Toba, where this kingdom opened trade relations with other European countries.\n" +
                    "\n" +
                    "On the other hand the Netherlands itself tried to instill its monopoly over the kingdom. This different politics prompted the next situation to give birth to the Tapanuli War which lasted for decades. In 1877 the missionaries in Silindung and Bahal Batu asked the Dutch colonial government for help from the threat of being expelled by Singamangaraja XII. Then the Dutch government and the evangelists agreed to not only attack the headquarters of Si Singamangaraja XII in Bakara but at the same time conquer all of Toba.\n" +
                    "\n" +
                    "On February 6, 1878 the Dutch troops arrived at Pearaja, the residence of the evangelist Ingwer Ludwig Nommensen. Then, along with the evangelists Nommensen and Simoneit as translators of the Dutch troops, they continued to go to Bahal Batu to build a defensive fort. However, the presence of this colonial army had provoked Sisingamangaraja XII, who then declared slumber (war) on February 16, 1878 and the attack on the Dutch post in Bahal Batu began.\n" +
                    "\n" +
                    "On March 14, 1878 Resident Boyle came with additional troops led by Colonel Engels as many as 250 soldiers from Sibolga. On May 1, 1878, Bangkara, the center of Si Singamangaraja's government, was attacked by colonial forces and on May 3, 1878 the entire Bangkara was conquered, but Singamangaraja XII and his followers were able to save themselves and were forced to flee. While the kings left in Bakara were forced by the Dutch to swear allegiance and the area was declared to be under the sovereignty of the Dutch East Indies government. Even though Bakara had been conquered, Singamangaraja XII continued to fight in a guerrilla manner, but until the end of December 1878 several areas such as Butar, Lobu Siregar, Naga Saribu, Huta Ginjang, Gurgur can also be conquered by the Dutch colonial forces.\n" +
                    "\n" +
                    "Between 1883-1884, Singamangaraja XII succeeded in consolidating his troops. Then, together with aid troops from Aceh, offensively attacked the Dutch positions, including Uluan and Balige in May 1883 and Batu Tangga in 1884.",
            "Sri Susuhunan Pakubuwono VI is one of the kings who once reigned in the Surakarta Hadiningrat Sunanate. Sri Susuhunan Pakubuwono VI has the title Sinuhun Bangun Tapa because he often does meditation or asceticism. Sri Susuhunan Pakubuwono VI was born with the real name Raden Mas Sapardan in Surakarta on April 26, 1807. He is a descendant of Sri Susuhan Pakubuwana V with his wife Raden Ayu Sosrokusumo who has a descendant of Ki Juru Martani. Although not the son of the Queen, Pakubuwono VI could be appointed king after his father who died in 1923 gave a will so that Pakubuwono VI was appointed king of the Kingdom of Surakarta.\n" +
                    "\n" +
                    "Pakubuwono VI officially ascended the throne on September 15, 1823. At the time Pakubuwono VI ruled, both the Kingdom of Yogyakarta and the Kingdom of Surakarta were facing a gloomy period. The influence of the Dutch in the two kingdoms was already very large. Even in the appointment of the king, the Dutch were decisive. The territory of the kingdom is getting narrower. Many areas were taken and ruled directly by the Dutch. In addition, rules and regulations were issued which greatly degraded the dignity of the kings. The nobles were pitted against each other, so that in the palace there were pro and anti-Dutch groups. Meanwhile, the people are getting worse and worse. As a result, both in Surakarta and in Yogyakarta there was general unrest.\n" +
                    "\n" +
                    "In 1825 war broke out led by Diponegoro, a prince of Yogyakarta. The war was known as the Diponegoro War (1825-1830). Pakubuwono VI was already preparing to join Diponegoro, but it couldn't be done because the Commander of the Dutch East Indies Army, General de Kock, quickly arrived in Surakarta. Therefore, he was forced to be passive, even forced to send troops to help the Dutch fight Diponegoro. After the Java War ended, the Dutch put quite heavy pressure on Pakubuwono VI. He was forced to sign an agreement containing the surrender of several areas to the Dutch. He refused to sign the agreement and irritated the Dutch. Due to increasing pressure, on June 6, 1830 Pakubuwono VI left the palace and went to Imogiri to visit the graves of his ancestors. Knowing this, the Dutch government accused him of preparing a rebellion, and was arrested and exiled. to Ambon. Pakubuwana VI died in Ambon on June 2, 1849.\n" +
                    "\n" +
                    "According to the official Dutch report, he died in an accident while cruising at sea. In 1957, the body of Pakubuwana VI was moved from Ambon to Astana Imogiri, a burial complex for the royal family of Mataram descent. Sunan Pakubuwana VI himself has been designated by the Indonesian government as a national hero based on S.K. President of the Republic of Indonesia No. 294 Year 1964, November 17, 1964. Recently, when his tomb was excavated, evidence was found that the skull of Pakubuwana VI had a hole in the forehead. According to the analysis of Gen. TNI Prince Haryo Jatikusumo (son of Pakubuwana X), the hole is the size of a Baker Riffle rifle bullet. Judging from the location of the hole, Pakubuwana VI clearly didn't die by suicide, let alone an accident while cruising. The anti-colonial king of Surakarta is thought to have been killed by being shot in the forehead.",
            "General Sudirman is one of the Heroes of the Indonesian National Revolution. In the history of the struggle of the Republic of Indonesia, he was the first and youngest Commander and General of the Republic of Indonesia. At a fairly young age, namely 31 years, Sudirman had become a general. In addition, he is also known as a persistent fighter. Even though he was suffering from severe lung disease, he continued to fight and guerrilla with his soldiers to fight the Dutch army in the Second Military Aggression.\n" +
                    "\n" +
                    "Sudirman was born in Purbalingga, Central Java on January 24, 1916. He comes from a simple family. His father is a worker at the Kalibagor sugar factory in Banyumas and his mother is a descendant of Wedana Rembang. Sudirman received his formal education from the Taman Siswa School. He then continued his education to HIK (teacher school) Muhammadiyah, Solo but did not finish. While studying there, he also participated in the activities of the Hizbul Wathan Scout organization. After that he became a teacher at the HIS Muhammadiyah school in Cilacap. He then devoted himself to being a teacher at HIS Muhammadiyah, Cilacap and a guide at the Hizbul Wathan Scout organization.\n" +
                    "\n" +
                    "During the Japanese colonial era, Sudirman joined the Defenders of the Homeland (Peta) army in Bogor. After Indonesia's independence from Japanese occupation, he managed to seize the weapons of the Japanese troops in Banyumas. Then he was appointed Battalion Commander in Kroya after completing his education. He then became the Commander of Division V/Banyumas after the TKR (People's Security Army) was formed, and was finally elected as Commander of the Indonesian Armed Forces (TNI Commander). The Palagan Ambarawa war against British troops and the Dutch NICA from November to December 1945 was the first major war he led. Because he succeeded in obtaining victory in this battle, President Soekarno appointed him General.\n" +
                    "\n" +
                    "Sudirman died on January 29, 1950 due to the severe tuberculosis he suffered. His body was buried at the Kusuma Negara Heroes Cemetery in Semaki, Yogyakarta. In 1997 he was awarded the title of General Posthumous with five stars, a rank that has only been held by three generals in Indonesia until now.",
            "Sutan Syahrir (Soetan Sjahrir) is an Indonesian national hero who was born in Padang Panjang, West Sumatra, March 5, 1909, is an intellectual, pioneer, and revolutionary for Indonesian independence. After Indonesia's independence, he became Indonesia's first politician and prime minister. He served as Prime Minister of Indonesia from 14 November 1945 to 20 June 1947. He also founded the Indonesian Socialist Party in 1948.\n" +
                    "\n" +
                    "Syahrir was born to Mohammad Rasad with the title Maharaja Soetan bin Soetan Leman with the title Soetan Palindih and Puti Siti Rabiah who came from Koto Gadang, Agam, West Sumatra. He attended elementary school at Europeesche Lagere School (ELS) and the best Meer Uitgebreid Lager Onderwijs (MULO) secondary school in Medan. In 1926, he entered the senior high school of Algemene Middelbare School (AMS) in Bandung, where the school was the most expensive school in the Dutch East Indies at that time. He also joined the Indonesian Student Theater Association (Batovis) as a director, screenwriter, and actor. The proceeds from the performance were used to finance the school he founded, Tjahja Volksuniversiteit (Light of the People's University). After that, he continued his education in the Netherlands at the Faculty of Law, University of Amsterdam. And there he studied socialism, he seriously studied the theories of socialism, at the end of 1931, Syahrir left his campus to return to his homeland and involved in the national movement. He then joined the Indonesian National Party (PNI Baru), which he chaired in June 1932.\n" +
                    "\n" +
                    "On June 26, 1946, in Surakarta, he was kidnapped by the opposition Unity of Struggle, which was dissatisfied with his diplomacy. The group wants full sovereignty (Merdeka 100%) which was initiated by Tan Malaka. Meanwhile, the cabinet in power at that time only demanded recognition of sovereignty over Java and Madura. President Soekarno was furious at the kidnapping and ordered the Surakarta Police to arrest the leaders of the group. After the kidnapping, he only served as Minister of Foreign Affairs, the duties as Prime Minister were taken over by President Soekarno. After leading the cabinet, he was appointed as an advisor to President Soekarno as well as a Mobile Ambassador. He founded the Socialist Party (PSI) in 1948. Syahrir died in Zurich, Switzerland, April 9, 1966 at the age of 57 years. He died in exile as a political prisoner and was buried at TMP Kalibata, Jakarta.",
            "Born on April 21, 1979, R. A Kartini herself is widely known as a figure of women's emancipation in Indonesia. The daughter of Raden Mas Adipati Ario Sosroningrat then went to school until the age of 12, the age when she began to be secluded. R.A Kartini herself received her education at Europese Lagere School. After being sequestered at the age of 12, Karini continued her study at home, practicing writing and reading. Because she has good Dutch language skills, she continues to study by sending letters to her friends in the Netherlands. sent by her friends. Young Kartini had a desire to promote Indonesian women, who at that time had only a very low social status. He pioneered this desire by teaching the girls around him to be able to write and read.\n" +
                    "\n" +
                    "On November 12, 1903, Kartini married the Regent of Rembang at the time, Raden Adipati Joyodiningrat. Her husband supported and gave her freedom, so that she was able to establish a women's school in the Rembang Regency office complex. This school continued to be developed until in 1912, a Women's School by the Kartini Foundation was officially established in Semarang. After that followed women's schools in Surabaya, Yogyakarta, Malang, Madiun, to Cirebon. Kartini and her husband were then blessed with a child born on September 13, 1904, who was named Soesalit Djojoadhiningrat. Unfortunately, four days after the birth of her baby, Kartini died. At that time she was 25 years old. Her struggle to elevate the status of Indonesian women was then supported by her close colleague, Mr. J.H. Abendanon, who collected letters from Kartini and later turned them into a book entitled After Dark Terbitlah Terang.",
            "Fatmawati, this native woman was born in Bengkulu on February 5, 1923 with the real name Fatimah. The name Fatimah was a gift from her parents. Fatmawati is a descendant of Hassan Din and Siti Chadijah whose parents are descendants of Puti Indrapura or commonly called a royal family from the Indrapura sultanate, Pesisir Selatan, West Sumatra. Fatmawati's father is also famous as one of the Muhammadiyah figures in Bengkulu. Fatmawati was educated and raised by both parents in Bengkulu. When growing up, Fatmawati married the First President of Indonesia Soekarno on June 1, 1943, at that time Fatmawati was 20 years old. From this marriage, Fatmawati automatically became the first First Lady of Indonesia from 1945 to 1967.\n" +
                    "\n" +
                    "Fatmawati is the third wife of the First President of Indonesia, Soekarno. The pair of Indonesian State Leaders were blessed with five sons and daughters, including Guntur Soekarnoputra, Megawati Soekarnoputri, Rachmawati Soekarnoputri, Sukmawati Soekarnoputri, and finally Guruh Soekarnoputra. which was expressly raised at the first ceremony of the Proclamation of Indonesian Independence in Jakarta, precisely on August 17, 1945.\n" +
                    "\n" +
                    "Fatmawati died on May 14, 1980 at the age of 57 years in Kuala Lumpur, Malaysia due to a heart attack while on her way home for Umrah from Mecca. Fatmawati is buried in Karet Bivou, Jakarta. Currently Fatmawati's name is used as the name of a hospital in Jakarta, Fatmawati Soekarno's name is also used as the name of an airport in Indonesia, precisely in Bengkulu, Fatmawati's hometown.",
            "Raden Dewi Sartika is the daughter of Raden Somanegara and Raden Ayu Permas. His father was a patih in Bandung who was very Nationalist. When his father and mother were arrested and exiled to Ternate (Maluku), then he was entrusted to his uncle, Patih Aria who lived in Cicalengka. Dewi was born in Bandung, December 4, 1884, she is a pioneering figure in education for women. Recognized as a National Hero by the Government of Indonesia in 1966\n" +
                    "\n" +
                    "Dewi Sartika is very persistent in fighting for the fate and dignity of women. On January 16, 1904, he founded the wife's school or school for women in Bandung. In 1910, the wife's school changed its name to Sakola Kautamaan Wife. The wife's school continues to receive positive attention from the community. The number of students increased, even the previously borrowed Kepatihan Bandung room was no longer enough to accommodate students. To overcome this, the Wife's School was then moved to a larger place. Over time, six years since its establishment, in 1910, the name of the Wife School was slightly updated to become the Wives Priority School. Changes are not only in the name, but the subjects also increase.\n" +
                    "\n" +
                    "Then in 1913, the Kautamaan wife organization was also established in Tasikmalaya. This organization houses the schools founded by Dewi Sartika. In 1929, Sakola Kautamaan Wife changed its name to Sakola Raden Dewi and by the Dutch East Indies government a new building was built which was large and complete. , and skilled. So for that, many lessons related to household development are given. To cover the school's operational costs, he worked hard to find funds. He did not feel all his hard work as a burden, but turned into inner satisfaction because he had succeeded in educating his people. One of the things that added to her enthusiasm was the encouragement from various parties, especially from Raden Kanduruan Agah Suriawinata, her husband, who had helped her a lot in realizing her struggle, both energy and thought.\n" +
                    "\n" +
                    "In 1947, due to the Dutch military aggression, Dewi Sartika took refuge along with the fighters who continued to fight against the Dutch to maintain independence. It was during this evacuation, on September 11, 1947, that the elderly Dewi Sartika died in Cinean, West Java. After the situation was safe, his grave was moved to Bandung.",
            "Cut Meutia is one of the female fighters from Aceh who has been recognized as an Indonesian national hero. Similar to other fighters from Tanah Rencong such as Tjoet Njak Dhien, Teuku Umar, Teuku Cik Di Tiro, and other Acehnese warrior figures, Cut Meutia is known as a brave figure and has a high fighting spirit and strong determination to get rid of the invaders.\n" +
                    "\n" +
                    "Cut Meutia fought against the Dutch with her husband Teuku Muhammad or better known as Teuku Tjik Tunong. Together they went through a long struggle, but in the end Teuku Tjik Tunong was arrested by the Dutch in March 1905. Teuku Tjik Tunong was then sentenced to death by the Dutch on the shores of Lhokseumawe. Before he died, he advised his friend Pang Nagroe to marry his wife and take care of his child after he died.\n" +
                    "\n" +
                    "According to the message of her late husband, Cut Meutia married Pang Nagroe and then joined the troops led by Teuku Muda Gantoe. In a battle against the Marechausée Corps at Paya Cicem, Pang Nagroe died in battle on 26 September 1910 while Cut Meutia survived. He and the other women who survived then fled into the forest.\n" +
                    "\n" +
                    "After the death of Pang Nagroe, Cut Meutia still continued to fight against the Dutch with a small army of his followers. They tried to attack and seize colonial outposts along their way to Gayo through the jungle. However, in the battle in Alue Kurieng on October 24, 1910, Cut Meutia was finally killed by the Dutch army's bullets. For his services, the government awarded the title of National Hero to Cut Meutia in 1964.",
            "Posthumous Lieutenant General TNI Mas Tirtodarmo Haryono or commonly known as MT Haryono is one of the seven heroes of the Indonesian revolution who died in the crocodile pit tragedy. During the Dutch occupation of Indonesia, MT Haryono had received education in various places. The first was at ELS, an elementary school-level education formed by the Dutch. MT Haryono also had time to continue his education at HBS, education at the level of public schools. Then turning to the Japanese occupation period, MT Haryono was sent to Ika Dai Gakko, a medical school during the Japanese occupation, but did not finish.\n" +
                    "\n" +
                    "When the independence of the Republic of Indonesia was declared, MT Haryono was in Jakarta and immediately joined other youths to defend Indonesia. This spirit of struggle was also continued with the entry of MT Haryono into the TKR (People's Security Army). In the early days of his appointment, MT Haryono got the position of Major. With his achievements, MT Haryono was finally promoted many times to get the position of Lieutenant General.\n" +
                    "\n" +
                    "In the G30S PKI tragedy that occurred on September 30, 1965, MT Haryono became one of the victims of the crocodile hole incident. He was one of the victims who was found dead in the crocodile pit. The victims of the G30S PKI incident were later dubbed the Heroes of the Revolution. Apart from MT Haryono, another revolutionary hero who also became a victim was General TNI (posthumous) Achmad Yani, Lt. Gen. (Posthumously) Siswondo Parman, Lt. Gen. (Posthumously) Suprapto, Major General. (Posthumous) Donald Isaac Pandjaitan, Major General. (Posthumously) Sutojo Siswomihardjo, Brigadier General. (Posthumously) Katamso Darmokusumo (died in Yogyakarta), Colonel Inf. (posthumously) Sugiono (died in Yogyakarta), Captain CZI (posthumously) Pierre Tendean, and Aipda (posthumously) Karel Satsuit Tubun. MT Haryono's body was buried at TMP Kalibata, Jakarta.",
            "General TNI (posthumous) Ahmad Yani is one of the Heroes of the Revolution, namely a hero who died as a result of the G 30 S/PKI rebellion. He was born in Purworejo on June 19, 1922. When he was in elementary school, he was educated at HIS in the Bogor area. He finished it in 1935. Then he continued his junior high school at MULO class B Afd. Bogor until 1938 which was then forwarded to AMS part B Afd. Jakarta. However, at this high school he could not finish it (only up to grade 2) because the Dutch East Indies Government announced a militia. Ahmad Yani, who had not finished high school, was then interested in the military world and enrolled in the Military Topography Service located in the Malang area, East Java which later continued its intensification in the Bogor area. This was the beginning of Ahmad Yani's career in the military. He graduated from military education with the rank of Sergeant. When Indonesia was colonized by Japan in 1942, Ahmad Yani enrolled to attend Heiho education in Magelang, Central Java. He then joined PETA (Defenders of the Homeland) Bogor branch.\n" +
                    "\n" +
                    "During the war for independence, Ahmad Yani also took part. His services are like he managed to confiscate Japanese weapons in Magelang. When TKR was born, he was made the TKR Commander for the Purworejo area. When the Dutch launched their first military aggression against Indonesia, Ahmad Yani and his troops managed to stem the Dutch attack in the Pingit area. During the second aggression, he was also appointed as Commander of Wehrkreise II to guard the Kedu area. When the DI/TII rebellion erupted, Ahmad Yani was assigned to overcome the rebellion in the Central Java area. Together with Fort Raiders troops, DI/TII was finally defeated. After the task was completed, he returned to the Army Staff. To further deepen his knowledge in the military field, in 1955 Ahmad Yani was sent to America to study at the Command and General Staff College in Fort Leaven Worth, Kansas, USA for nine months. A year later he continued his military school for two months in England taking the Special Warfre Course. When the PRRI rebellion broke out in West Sumatra in 1958, Ahmad Yani, who at that time held the rank of Colonel, was asked to become Commander of the 17 August Operations Command who later led the suppression of the rebellion. and his achievements, in 1962, Ahmad Yani was appointed by President Soekarno as Minister/Commander of the Army.\n" +
                    "\n" +
                    "From a political point of view, Ahmad Yani did not agree and was always at odds with the PKI. When the PKI attempted to form a 5th generation consisting of armed farm workers, Ahmad Yani immediately rejected it. This is the reason that he was included in the target of kidnapping and murder by the PKI in 1965. Together with seven other Army officers, he was kidnapped and killed and his body was put into an old well in the Lubang Buaya area through the G30 S/PKI rebellion operation. in the early hours of October 1, Ahmad Yani was shot in front of his bedroom. After a search was carried out the next day, Ahmad Yani's body was then buried with honor at the Kalibata Heroes Cemetery, South Jakarta. He and the seven officers who were victims of the PKI's ferocity were later named Heroes of the Revolution and posthumously promoted to Lieutenant General.",
            "Posthumous Lieutenant General TNI Siswondo Parman or better known as S. Parman is one of the heroes of the Indonesian revolution and a prominent Indonesian military figure. S. Parman died after being killed in the G30S PKI incident. S. Parman later earned the title of Posthumous Lieutenant General. S. Parman was the sixth of eleven children born in Wonosobo, Central Java on August 4, 1918. His father, Kromodihardjo, worked as a trader. S. Parman has an older brother named Ir. Sakirman where later his brother will become a high-ranking officer in the Politburo CC PKI (a kind of Syuro Council or Advisory Council of Political Parties now).\n" +
                    "\n" +
                    "Even though Kromodihardjo is only a trader in Wonosobo Market, he always tries to ensure that his children can get the highest education possible. Parman completed his education at HIS (Hollandsch Inlandsche School) or Dutch Elementary School in Wonosobo. Then he continued to MULO (Meer Uitgebried Lager Onderwijs) or Junior High School in Yogyakarta. After he graduated, Parman should have continued to AMS (Algemeene Middelbare School) which was equivalent to a high school level but because his father died in 1937 Parman did not go to school for almost two years. Parman then helped his mother trade in Wonosobo Market. After finding the right time, Parman resumed his studies at AMS. In accordance with his father's wishes, Parman then entered the Medical College (STOVIA) in Jakarta. He could not finish his medical school because of the Japanese invasion in 1942. One day while Parman was in Wonosobo, he met the Japanese military police, Kenpetai who said if they need someone who can speak English as a translator. From then on, Parman, who is fluent in English, followed Kenpetai to Yogyakarta. Despite helping Japan, Parman's sense of nationalism remained high. He keeps in touch with his friends who are fighting secretly against the Japanese.\n" +
                    "\n" +
                    "After Indonesia's independence, Parman chose the military world as his place of service to the country. During Military Aggression II, Parman joined the guerrillas outside the city. After the aggression, Parman was educated at the Koninklijke Militaire Academie (a kind of AKMIL) in Breda, the Netherlands. Year after year, Parman's career continued to climb, he was later appointed Assistant I to the Men Commander for Intelligence with the rank of Brigadier General. In August 1964, he was promoted again to Major General. By the time he held the position of Assistant I for Intelligence, the PKI's influence had extended to almost all areas of the state. The PKI's main opponent was the Army. The PKI spread public opinion that the Army intended to overthrow the leadership of President Soekarno. Therefore, the PKI urged the President to form a Fifth Force whose members were armed workers and peasants.\n" +
                    "\n" +
                    "At that time, Parman was one of the most vehemently opposed to the plan to form the Fifth Force. His refusal and his position as an intelligence official who knew a lot about the PKI made him the main target of the PKI. Finally, in the early hours of October 1, 1965, Parman was kidnapped by a group of G30S/PKI led by Serma Satar from the Tjakrabirawa Regiment. At Lubang Buaya, after being brutally tortured, Parman finally breathed his last. His body was only found on October 4, 1965 and buried on October 5, 1965 at TMP Kalibata. Ironically, one of the drivers of Parman's kidnapping was none other than his own brother, Ir. Sakirman who was a high-ranking officer in the Politburo CC PKI.",
            "Posthumous Lieutenant General TNI R. Suprapto, a hero of the Indonesian revolution who became a victim in the G30SPKI in 1965 and is now buried in the Kalibata Heroes Cemetery, Jakarta. The man who was born on August 24, 1920, completed his education at the MULO school which is equivalent to junior high school and AMS which is equivalent to high school now in 1941.\n" +
                    "Suprapto then chose to enter a Dutch military school called Koninklijke Militaire Akademie in Bandung. However, Suprapto did not complete his military education due to the Japanese invasion of Indonesia. He was even a Japanese prisoner at the time, but Suprapto managed to escape.\n" +
                    "\n" +
                    "In the early days of Indonesian independence, Suprapto joined the People's Security Army (TKR). He also participated in the battle against the Japanese in Cilacap and succeeded in disarming the Japanese soldiers. The man from Purwokerto was also appointed as an adjutant to the Commander in Chief Sudirman in 1946. In September 1949 he was then appointed Chief of Army and Territorial Staff IV/Diponegoro in Semarang and in 1951 moved to TNI Headquarters in Jakarta as Army Staff .\n" +
                    "\n" +
                    "In the early hours of October 01, Suprapto, who was unable to sleep at the time because of a toothache he was suffering from, was approached by a group of people, claiming to be the presidential guard (Cakrabirawa), who said that he had been summoned by president Sukarno to appear. Suprapto was then loaded into a truck and taken to Lubang Buaya, a suburb of Jakarta, along with 6 other people. That evening, General Suprapto and six other people were shot dead and thrown into an old well. Only on October 5, the bodies of the murder victims could be removed and buried in the Kalibata Heroes Cemetery. On the same day, President Sukarno issued Presidential Decree no. 111/KOTI/1965, which inaugurated Suprapto and the other victims of Lubang Buaya as Revolutionary Heroes.",
            "Posthumous Major General TNI Donald Isaac Panjaitan is one of the famous revolutionary heroes in Indonesia. Even though he died at a young age of 40, his struggles in defending his homeland deserve to be applauded.\n" +
                    "\n" +
                    "Panjaitan is a hero who has attended elementary school to college at the Associated Command and General Staff College, United States. While still in Indonesia, he was a member of the Gyugun in Pekanbaru, Riau and formed the People's Security Army (TKR) which later became TNI. He occupied the position of battalion commander at TKR which later became the Educational Commander of Division IX/Banteng in Bukittinggi in 1948. After that, he became Chief of General Staff IV (Supplay) of the Sumatran Army Command.\n" +
                    "\n" +
                    "He also won the leadership of the Emergency Government Struggle of the Republic of Indonesia (PDRI) when the Second Dutch Military Aggression occurred. After the Dutch Military Aggression II ended, he was reappointed as Chief of Staff for Army and Territory Operations (T&T) I Bukit Barisan in Medan which was then transferred to Palembang to become Chief of Staff of T&T II/Sriwijaya.\n" +
                    "\n" +
                    "After returning to study in the United States, Panjaitan uncovered the secrets of the PKI regarding the shipment of weapons from the People's Republic of China that were put in building material crates. These weapons were expected to be used by the PKI to launch an insurgency. Panjaitan's action in revealing PKI secrets sparked anger from the PKI. On October 1, 1965, a group of members of the September 30th Movement came to Panjaitan's house. When Panjaitan tried to escape, he was shot by PKI members and died. His body was taken and dumped in the Crocodile Hole. On October 4, Panjaitan's body was taken and properly buried at TMP Kalibata, Jakarta. Thanks to his courage to defend the country, Panjaitan was awarded the title of Revolutionary Hero by the Indonesian government.",
            "Sutoyo Siswomiharjo received HIS and AMS education in Semarang. Then he continued his education at the Civil Service Education Center in Jakarta. Before becoming a soldier, Sutoyo served as a Middle/III Officer in Purworejo Regency. His career in the military field began by serving as an Army Police during the 1945 independence struggle. After that his career continued to climb so that in 1961 he was promoted to Colonel and served as IRKEHAD, then in 1964 he was promoted to Brigadier General.\n" +
                    "\n" +
                    "Pak Toyo, Sutoyo's nickname, was known to the Indonesian people when he became a victim of the G30S/PKI on October 1, 1965. Prior to the incident, Pak Toyo had some bad feelings. However, in the midst of this uneasy feeling, he ordered his aides to carefully plan the commemoration of ABRI Day 5 October 1965 for his aides. This hunch turned out to be proven on October 1 at 04.00 pm Brigadier General Sutoyo was kidnapped by troops led by Serma Surono from Men Cakrabirawa with the strength of 1 platoon. At bayonet, they asked the housekeeper to hand over the key to the door leading to the living room. After the door was opened by Brigadier General Sutoyo, private personnel Suyadi and Praka Sumardi entered the house, they said that Brigadier General Sutoyo was summoned by the President. The two men took Brigadier General Sutoyo out of the house until the door to the yard was handed over to Serda Sudibyo. Flanked by Serda Sudibyo and Pratu Sumardi, Brigadier General Sutoyo walked out of the yard leaving the place to be taken to Lubang Buaya. Pak Toyo died being persecuted in that place, and was awarded the title Hero of the Revolution.",
            "Posthumous Captain Pierre Andreas Tendean is an Indonesian military officer who became one of the victims of the September 30th Movement in 1965. He started his military career by becoming an intelligence officer and was later appointed as an adjutant to General Abdul Haris Nasution with the rank of first lieutenant, he was promoted to captain posthumously after his death. Tendean was buried in the Kalibata Heroes Cemetery and along with six other G30S victims, he was declared a Hero of the Indonesian Revolution on October 5, 1965.\n" +
                    "\n" +
                    "Pierre Andreas Tendean was born on February 21, 1939 in Batavia (now Jakarta), the Dutch East Indies to Dr. A.L Tendean, a doctor of Minahasa blood, and Cornet M.E, attacked an Indo woman of French descent. Pierre was the second of three children; his brother and sister were named Mitze Farre and Rooswidiati, respectively. Tendean attended elementary school in Magelang, then continued his junior and senior high school in Semarang where his father served. Since childhood, he really wanted to become a soldier and enter a military academy, but his parents wanted him to become a doctor like his father or an engineer. Because of his strong determination, he also managed to join the Army Engineering Academy (ATEKAD) in Bandung in 1958.\n" +
                    "\n" +
                    "In 1962 Tandean graduated from the military academy with the rank of second lieutenant, and became the Platoon Commander of the 2nd Combat Engineer Battalion of Kodam II/Bukit Barisan in Medan. A year later, he attended an intelligence school in Bogor. After graduating, he was assigned to the Army Intelligence Center Service (DIPIAD) to spy on Malaysia in connection with the confrontation between Indonesia and Malaysia; he was tasked with leading a group of volunteers in several areas to infiltrate Malaysia. On April 15, 1965, Tendean was promoted to first lieutenant, and was assigned as an adjutant to General Abdul Haris Nasution.\n" +
                    "\n" +
                    "On the morning of October 1, 1965, troops of the September 30th Movement (G30S) came to Nasution's house with the aim of kidnapping him. Tendean who was sleeping in the back room of General Nasution's house woke up to the sound of gunfire and noise and immediately ran to the front of the house. He was arrested by a group of G30S who mistook him for Nasution because of the dark conditions of the house. Nasution himself managed to escape by jumping over the fence. Tendean was then taken to a house in the Lubang Buaya area with six other high-ranking officers. He was shot dead and his body thrown into an old well along with the bodies of six other officers. Together with the six other officers, Tendean was buried in the Kalibata Heroes Cemetery, Jakarta. To appreciate his services, Tendean was awarded the title Hero of the Indonesian Revolution on October 5, 1965 based on the Decree of the President of the Republic of Indonesia No. 111/KOTI/Year 1965.",

    };
}
