package com.prakpapb2.utils;

public class DataPahlawanId {

    static final int[] id = {
            1,
            2,
            3,
            4,
            5
    };

    static final String[] photoPahlawan = {
            "https://cdn1-production-images-kly.akamaized.net/SoUvACur9TC9Kf5P_T4zLIV-DsQ=/640x853/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/1238080/original/005070900_1463635462-dr_Soetomo_-_dr_Sutomo.jpg",
            "https://scontent.fcgk30-1.fna.fbcdn.net/v/t31.18172-8/23592385_507734569596894_1225625643885781021_o.jpg?_nc_cat=104&ccb=1-3&_nc_sid=973b4a&_nc_ohc=gFfPmtrifrcAX-8Y9xf&_nc_ht=scontent.fcgk30-1.fna&oh=362ad54a42b6519e3772df82abbea259&oe=60D178A4",
            "https://3.bp.blogspot.com/-0b8OK4m2K0k/WIAa-cBDUBI/AAAAAAAAREA/Qt-faNv9tpsbixCBOaI-h5ISFgDhKHGiACLcB/w600/Tokoh%2BPeletak%2BDasar%2BPendidikan%2BNasional.jpg",
            "https://www.matakota.id/uploads/images/news/1501765097362.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Portret_van_de_schrijver_Multatuli_%28cropped%29.jpg/330px-Portret_van_de_schrijver_Multatuli_%28cropped%29.jpg",
            "http://3.bp.blogspot.com/-3CQivNjiJqo/TWJXeHI6BfI/AAAAAAAAAV8/1RbC_JMNXtU/s320/cut-nyak-dhien.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cut_Nyak_Meutia.jpg/263px-Cut_Nyak_Meutia.jpg",
            "https://www.inhilklik.com/assets/berita/original/83162943273-63828780781-20200218_153258.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/5/53/Sri_Susuhunan_Pakubuwono_VI.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sudirman.jpg/729px-Sudirman.jpg",
            "https://files.kajanglako.com/images/uploads/kj-gambar-20200411_o701VS.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg",
            "https://kebudayaan.kemdikbud.go.id/muspres/wp-content/uploads/sites/38/2020/02/images.jpg",
            "https://cdn.idntimes.com/content-images/community/2020/05/dewi-sartika-92820ae8f02b5cfd1ff77967b3f9e760.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/MT_Haryono.jpg/330px-MT_Haryono.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Ahmad_Yani.jpg/300px-Ahmad_Yani.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/S_Parman.jpg/330px-S_Parman.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Soeprapto.jpg/330px-Soeprapto.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Panjaitan.jpg/330px-Panjaitan.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Sutoyo.jpg/330px-Sutoyo.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/e/ec/Tendean.jpg",
            ""

    };

    static final String[] namaPahlawan = {
            "dr.Soetomo",
            "Ir.Soekarno (ID)",
            "Ki Hajar Dewantara",
            "dr.Cipto Mangunkusumo",
            "Douwes Dekker",
            "Cut Nyak Dhien",
            "Cut Meutia",
            "Sisingamangaraja XII",
            "Pakubowono",
            "Jenderal Soedirman",
            "Sutan Sjahrir",
            "R.A. Kartini",
            "Fatmawati",
            "Raden Dewi Sartika",
            "Cut Meutia",
            "Mayjen MT Haryono",
            "Jenderal Ahmad Yani",
            "Mayjen S.Parman",
            "Mayjen R.Suprapto",
            "Brigjen D.I Panjaitan",
            "Brigjen Sutoyo",
            "Lettu Pierre Tandean"
    };

    static final String[] deskripsiPahlawan = {
            "Dokter Soetomo yang bernama asli Soebroto, lahir di Ngepeh, Jawa Timur, 30 Juli 1888 dan wafat di Surabaya, tanggal 30 Mei 1938 dan dimakamkan di Surabaya. Beliau adalah tokoh pendiri Budi Utomo juga Pahlawan Kemerdekaan Nasional berdasarkan Surat keputusan Presiden Republik Indonesia No.657 Tahun 1961, tanggal 27 Desember 1961\n" +
                    "\n" +
                    "Dr.Sutomo belajar sekolah Dokter di STOVIA dan sering melakukan diskusi bersama rekan-rekannya, Atas saran dr. Wahidin Soedirohoesodo, Soetomo mendirikan Boedi Oetomo pada tanggal20 Mei 1908.Boedi Oetomo merupakan organisasi modern pertama yang lahir di Indonesia dan Soetomo diangkat sebagai ketuanya. Organisasi ini bertujuan untuk memajukan pendidikan dan kebudayaan sebagai jalan untuk membebaskan bangsa dari penjajahan.\n" +
                    "\n" +
                    "Tahun 1911 Soetomo tamat darii STOVIA kemudian mendapat tugas di Semarang. Dari sana Ia dipindahkan ke Tuban, kemudian ke Lubuk Pakam (Sumatera Utara) dan akhirnya ke Malang. Di Kota Malang Ia harus membasmi wabah pes yang sedang melanda daerah itu.\n" +
                    "\n" +
                    "Karena seringnya berpindah-pindah tempat tugas maka Soetomo mendapat banyak pengalaman. Ia semakin banyak mengetahui kesengsaraan rakyat dan secara langsung dapat membantu mereka. Sebagai seorang dokter Ia membantu tanpa mengharapkan imbalan dari pasiennya, adakalanya pasien dibebaskan dari pembayaran.\n" +
                    "\n" +
                    "Pada tahun 1919, Soetomo mendapat kesempatan memperdalam pengetahuan di negeri Belanda. kesibukannya belajar tidak memadamkan minatnya pada politik. Di negeri Belanda Ia bergabung dengan Perhimpunan Indonesia. Sekembalinya ke Indonesia, Ia melihat ada kelemahan dalam Boedi Oetomo. Di Indonesia saat itu sudah banyak berdiri partai. Ia menyarankan agar Boedi Oetomo bergerak dalam bidang politik dan keanggotannya terbuka untuk semua warga masyarakat.\n" +
                    "\n" +
                    "Tahun 1924, Soetomo mendirikan Indonesische Studie Club (ISC) yang merupakan wadah bagi kaum terpelajar. ISC berhasil mendirikan asrama pelajar, sekolah tenun, bank kredit, koperasi dan sebagainya.\n" +
                    "\n" +
                    "Tahun 1931, ISC berganti nama menjadi Persatuan Bangsa Indonesia (PBI). Di bawah pimpinan Soetomo, PBI berkembang dengan pesat. karena tekanan pemerintah Belanda yang semakin keras maka pada tahun 1935 Boedi Oetomo dan PBI digabung menjadi satu dengan nama Partai Indonesia Raya (Parindra), yang berjuang untuk mencapai Indonesia merdeka.\n" +
                    "\n" +
                    "Dokter Soetomo juga aktif dalam bidang kewartawanan dan bahkan memimpin beberapa surat kabar. Kesibukan dan perjuangannya menjadikan kesehatannya melemah, Ia meninggal dunia di Surabaya 30 Mei 1938. Untuk menghormati jasa-jasanya, dr. Soetomo diangkat sebagai Pahlawan Kemerdekaan Nasional berdasarkan  Surat keputusan Presiden RI No.657/1961. ",
            "Ir. Soekarno adalah presiden pertama Republik Indonesia, sekaligus tokoh proklamator RI. \n" +
                    "\n" +
                    "Bung Karno lahir di Surabaya, 6 Juni 1901 dan meninggal di Jakarta, 21 Juni 1970. Pada tanggal 17 Agustus 1945, Indonesia memplokamirkan kemerdekaannya. Pada tanggal 18 Agustus 1945, Soekarno dan Mohammad Hatta diangkat oleh PPKI menjadi Presiden dan Wakil Presiden Republik Indonesia. Pada tanggal 29 Agustus 1945 pengangkatan Presiden Soekarno dan Wakil Presiden Mohammad Hatta dikukuhkan oleh KNIP.",
            "Raden Mas Soewardi Soerjaningrat, sejak 1922  menjadi Ki Hadjar Dewantara, beberapa bahasa  Jawa untuk menulis suara Ki Hajar Dewantoro, dilahirkan di Yogyakarta, 2  Mei 1889 dan wafat di Yogyakarta, 26 April 1959 di usia 69, adalah aktivis gerakan kemerdekaan  Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda.\n" +
                    "\n" +
                    "Beliau adalah pendiri Perguruan Taman  Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi rakyat  jelata adat untuk dapat memperoleh hak atas pendidikan serta aristokrasi  dan Belanda.\n" +
                    "\n" +
                    "Tanggal  lahir sekarang diperingati di Indonesia sebagai Hari Pendidikan  Nasional. Bagian dari penciptaan slogan, tut wuri handayani, menjadi  slogan Departemen Pendidikan Nasional Indonesia. Namanya diabadikan  sebagai salah satu nama dari kapal perang Indonesia KRI Ki Hajar  Dewantara. Gambar dirinya diabadikan pada tagihan 20.000 dolar tahun 1998 emisi.\n" +
                    "\n" +
                    "Beliau dikukuhkan sebagai  pahlawan nasional untuk-2 oleh Presiden, Soekarno, pada 28 November  1959 (Keputusan Presiden Republik Indonesia Nomor 305 Tahun 1959,  tanggal 28 November 1959).\n" +
                    "\n" +
                    "Pengalaman mengajar Beliau digunakan  untuk mengembangkan konsep mengajar bagi sekolah yang ia dirikan pada 3  Juli 1922: Nationaal Onderwijs Instituut Tamansiswa atau Tamansiswa  National University.\n" +
                    "\n" +
                    "Saat  Beliau mencapai usia 40 tahun menurut hitungan penanggalan Jawa, ia  mengganti namanya menjadi Ki Hadjar Dewantara. Dia tidak lagi  menggunakan gelar kebangsawanan di depan namanya. Ini berarti bahwa dia  bisa bebas dekat dengan rakyat, baik fisik dan mental.\n" +
                    "\n" +
                    "Semboyan  dalam sistem pendidikan yang menggunakan sekarang sangat terkenal di  kalangan pendidikan di Indonesia. Secara keseluruhan, slogan membacanya  dalam bahasa Jawa yang dinyanyikan Tulodo ngarso ing, ing Madyo Mangun  Karso, tut wuri handayani. \"Di depan memberi contoh, di tengah memberi  semangat, memberi dorongan balik\". Slogan ini masih digunakan dalam  pendidikan masyarakat Indonesia, terutama di sekolah-sekolah Perguruan  Tamansiswa.",
            "Tjipto Mangoenkoesoemo dikenal sebagai salah satu tokoh pergerakan kemerdekaan Indonesia yang juga dijuluki sebagai anggota Tiga Serangkai bersama Ernest Douwes Dekker dan Ki Hajar Dewantara. Selain mengabdikan hidupnya sebagai seorang dokter, Tjipto juga bergerak di bidang politik guna menentang penjajahan Belanda. Ketika kedua rekannya dalam Tiga Serangkai berubah haluan bergerak di bidang pendidikan, ia tetap setia berada di jalur politik hingga akhir hayatnya.\n" +
                    "\n" +
                    "Tjipto tldaklah berasal dari keluarga priyayi yang memiliki kedudukan sosial yang tinggi. Namun karena kecerdasannya, ia mampu bersekolah di STOVIA atau Sekolah Pendidikan Dokter Hindia. Ketidakpuasannya terhadap peraturan-peraturan di STOVIA serta keprihatinannya terhadap kondisi masyarakat Indonesia di bawah jajahan kolonial Belanda saat itu membuat dirinya aktif menuangkan segala pemikiran dan kritisinya dalam harian De Locomotief sejak tahun 1907. Ia juga menyebarkan pandangan-pandangannya yang sarat akan nilai-nilai politik dengan bergabung dalam organisasi Budi Utomo. Tetapi pada akhirnya ia memutuskan untuk mengundurkan diri dari Budi Utomo karena adanya perpecahan ideologi dalam tubuh organisasi yang terbentuk pada tanggal 20 Mei 1908 ini. Ia kemudian mendirikan Indische Partij bersama Ernest Douwes Dekker dan Ki Hajar Dewantara pada tanggal 25 Desember 1912. Saat itu Indische Partij merupakan satu-satunya organisasi yang secara terang-terangan bergerak di bidang politik dan bertujuan mencapai Indonesia merdeka. Pada tahun 1913, ketiga tokoh pendiri Indische Partij tersebut ditangkap dan dibuang ke Belanda karena aksi propaganda anti Belanda yang mereka tuangkan dalam artikel di harian De Express yang berisi penentangan mereka terhadap perayaan kemerdekaan Belanda di Indonesia. Kehadiran mereka di Belanda memberikan pengaruh penting terhadap Indische Vereeniging, perkumpulan mahasiswa Indonesia di Belanda, dalam mendukung pergerakan kemerdekaan. \n" +
                    "\n" +
                    "Karena sakit, Tjipto dipulangkan ke Jawa pada tahun 1914. Setelah ia kembali, ia bergabung dengan Insulinde, suatu perkumpulan yang menggantikan Indische Partij yang kemudian berubah nama menjadi Nationaal-Indische Partij (NIP). Di tahun 1918, ia menjadi anggota Volksraad (Dewan Rakyat) bentukan Belanda. Ia memanfaatkan Volksraad sebagai tempat untuk menyatakan aspirasi dan kritik kepada pemerintah mengenai masalah sosial dan politik. Karena dianggap berbahaya, pemerintah Hindia Belanda pun membuang Tjipto ke Bandung. Di sana ia bertemu dengan Soekarno. Tjipto juga dibuang untuk kesekian kalinya pada tahun 1928 karena didakwa turut andil dalam pemberontakan yang dilakukan kaum komunis. Ia dibuang ke pulau Banda namun akhirnya dikembalikan ke pulau Jawa karena kondisi kesehatannya yang memburuk.   ",
            "Eduard Douwes Dekker, yang kemudian dikenal dengan nama Multatuli, lahir pada 2 Maret 1820 di Amsterdam, Belanda. Ia berasal dari keluarga sederhana. Ayahnya seorang nakhoda bernama Engel Douweszoon Dekker sedangkan ibunya bernama Sytske Eeltje Klein. Ia anak keempat. \n" +
                    "\n" +
                    "Pada usia 18 tahun ia pergi ke Hindia Belanda untuk mengadu nasib. Di tahun 1839 ia menjadi pegawai negeri di Hindia Belanda. Pada 1842 ia di pindahkan ke Sumatra Barat dan menjadi kontrolir di Natal. Tetapi kemudian dipindahkan ke Padang karena tidak bisa mempertanggungawabkan isi kas yang dipegangnya. Sejak itu ia akrab dengan kemiskinan. \n" +
                    "\n" +
                    "Pada Semtember 1845 ia bertugas berturut-turut di Karawang, Bagelen, dan Manado. Ia bertemu dengan Tine, calon istrinya di Parakan Salak. Setelah bertunangan pada 18 Agustus 1845, mereka menikah pada 10 April 1846.\n" +
                    "\n" +
                    "Eduard diangkan menjadi komis di kantor residen di Purworejo sebulan setelah menikah. Di bulan Oktober 1848 ia menjadi sekretaris di Manado. Kemudian ia diangkan menjadi asisten residen di Ambon pada 1851. Karena terlalu lelah ia kemudian jatuh sakit.maka pada tahun 1852 ia berlibur ke Belanda bersama istrinya. \n" +
                    "\n" +
                    "Pada 1855 ia kembali ke Batavia setelah kehidupnya di Belanda hancur karena hidupnya yang urakan yang membuat utangnya menumpuk. Bersama keluarganya ia tinggal di Bogor dan menerima uang tunggu. Ia akhirnya bisa berhubungan dengan Duymaer van Twist, gubernur jenderal yang mengangkatnya menjadi asisten residen di Lebak dan berkedudukan di Rangkasbitung.\n" +
                    "\n" +
                    "Pada 24 Februari 1856 ia mengirim laporan pada Residen Brest di Serang. Ia menuduh bupati Lebak menyalahgunakan kekuasaannya dan dicurigai melakukan pemerasan. Dua hari setelah menerima laporan itu Residen Brest van Kempen segera menuju Lebak untuk membicarakan persoalan tersebut.\n" +
                    "\n" +
                    "Kempen meminta Douwes Dekker untuk menyerahkan arsip dan bukti kepadanya. Tetapi Dekker menolak, ia ingin memikul semua tanggung jawbnya sendiri. Akhirnya kempen langsung melapor kepada gubernur jenderal Twist dan meminta Dekker dipecat karena tidak patuh. Gubernur jenderal tidak memecatnya, hanya memindahkannya ke Ngawi. Douwes Dekker menolak pemindahan dan ia minta berhenti. Pada tanggal 20 April 1856 ia meninggalkan lebak dan kembali ke Belanda, sedangkan istri dan anaknya ditinggalkan di Batavia. \n" +
                    "\n" +
                    "Pada Januari 1858 ia tiba di Brussel, Belgia. Di kamar losmen Au Prince Belge, selama satu bulan di musim gugur tahun 1859 ia menulis buku Max Havelaar. Ternyata buku itu tidak berkenan di hati penguasa Belanda karena berisi kritik atas perlakuan buruk para penjajah terhadap orang-orang pribumi di Hindia-Belanda, dan membujuk Dekker untuk tidak menerbitkan naskah itu. Dekker bersedia asal ia diangkat menjadi residen di Pasuruan. Selain itu ia minta persekot besar untuk melunasi utang-utangnya dan akhirnya ia minta Bintang Ksatria Singa Belanda. Setelah tawar menawar, ia juga ingin diangkat menjadi anggota Dewan Hindia Belanda. \n" +
                    "\n" +
                    "Permintaan itu ditolak, maka terbitah buku Max Havelaar dengan menggunakan nama pena Multatuli yang berarti  Aku Yang Menderita.  Ternyata Max Havelaar laris. Tetapi Dekker sendiri tetap hidup dalam kemiskinan dan kesehatannya menurun. Sebelumnya  Dekker banyak menulis buku lainnya, tetapi Max Havelaar yang membuat namanya menjadi terkenal.Pada tanggal 19 Februari 1887, dua minggu sebelum ulang tahunnya ia meninggal dunia di tepi sungai Rhein, Jerman. ",
            "Cut Nyak Dhien merupakan pahlawan nasional wanita Indonesia asal Aceh. Ia berasal dari keluarga bangsawan yang agamis di Aceh Besar. Ketika usianya menginjak 12 tahun, Cut Nyak Dhien dinikahkan dengan Teuku Cek Ibrahim Lamnga yang juga berasal dari keluarga bangsawan.\n" +
                    "\n" +
                    "Semenjak Belanda menyerang Aceh untuk pertama kalinya pada tanggal 26 Maret 1873, semangat Cut Nyak Dhien untuk memerangi pasukan kolonial Belanda mulai timbul. Peristiwa gugurnya Teuku Cek Ibrahim Lamnga dalam peperangan melawan Belanda pada tanggal 29 Juni 1878 semakin menyulut kemarahan dan kebencian wanita pemberani ini terhadap kaum penjajah tersebut. Ia kemudian menikah lagi dengan Teuku Umar yang juga merupakan pahlawan nasional Indonesia di tahun 1880.\n" +
                    "\n" +
                    "Awalnya Cut Nyak Dhien menolak pinangan Teuku Umar, tetapi ia akhirnya setuju untuk menikah dengan pria yang masih memiliki garis kekerabatan dengan dirinya ini setelah Teuku Umar menyanggupi keinginannya untuk ikut turun ke medan perang. Ia sangat ingin mengenyahkan Belanda dari bumi Aceh dan menuntut balas atas kematian suaminya terdahulu.\n" +
                    "\n" +
                    "Bersama dengan Teuku Umar dan para pejuang Aceh lainnya, Cut Nyak Dhien pun gencar melakukan serangan terhadap Belanda. Dalam masa perjuangan tersebut, Cut Nyak Dhien sempat mendapat makian dari Cut Meutia yang juga pejuang wanita dari Aceh lantaran keputusan suaminya, Teuku Umar, menyerahkan diri pada Belanda dan bekerja sama dengan mereka. Padahal Teuku Umar tidak benar-benar menyerahkan diri pada Belanda. Hal ini ia lakukan sebagai taktik untuk mendapatkan peralatan perang Belanda. Setelah niatnya terlaksana dan ia kembali pada Cut Nyak Dhien  dan para pengikutnya, Belanda yang merasa telah dikhianati oleh Teuku Umar melancarkan operasi besar-besaran untuk memburu pasangan suami-istri tersebut. Teuku Umar pun akhirnya gugur dalam pertempuran di Meulaboh pada tanggal 11 Februari 1899.\n" +
                    "\n" +
                    "Sepeninggal suaminya, Cut Nyak Dhien masih meneruskan perlawanan kepada Belanda. Namun, sakit encok yang dideritanya dan kondisi matanya yang mulai rabun membuat para pengawalnya merasa kasihan dan akhirnya membuat kesepakatan dengan Belanda bahwa Cut Nyak Dhien boleh ditangkap asalkan diperlakukan secara terhormat, bukan sebagai penjahat perang.\n" +
                    "\n" +
                    "Setelah Belanda menyetujui kesepakatan ini, Cut Nyak Dhien pun akhirnya ditangkap dan dibawa ke Banda Aceh. Ia kemudian dibuang ke Sumedang tanggal 11 Desember 1905 dan menghembuskan napas terakhirnya di sana tanggal 6 November 1908. Jenazah Cut Nyak Dhien kemudian dikebumikan di Gunung Puyuh, Sumedang.   ",
            "Cut Meutia merupakan salah satu pejuang wanita dari Aceh yang telah diakui sebagai pahlawan nasional Indonesia. Sama halnya dengan para pejuang dari Tanah Rencong lainnya seperti Cut Nyak Dhien, Teuku Umar, Teuku Cik Di Tiro, dan tokoh pejuang Aceh lainnya, Cut Meutia dikenal sebagai sosok pemberani dan memiliki semangat juang yang tinggi serta tekad kuat untuk mengenyahkan para penjajah.\n" +
                    "\n" +
                    "Cut Meutia bertempur melawan Belanda bersama suaminya Teuku Muhammad atau lebih dikenal sebagai Teuku Tjik Tunong. Mereka bersama-sama melalui perjuangan yang panjang, namun pada akhirnya Teuku Tjik Tunong ditangkap oleh pihak Belanda pada bulan Maret tahun 1905. Teuku Tjik Tunong kemudian dijatuhi hukuman mati oleh Belanda di tepi pantai Lhokseumawe. Sebelum meninggal, ia berpesan pada sahabatnya Pang Nagroe agar mau menikahi istrinya dan merawat anaknya sepeninggal dirinya kelak.\n" +
                    "\n" +
                    "Sesuai pesan mendiang suaminya, Cut Meutia pun menikah dengan Pang Nagroe lalu bergabung bersama pasukan pimpinan Teuku Muda Gantoe. Dalam suatu pertempuran melawan Korps Marechausée di Paya Cicem, Pang Nagroe tewas dalam peperangan pada tanggal 26 September 1910 sedangkan Cut Meutia berhasil selamat. Ia bersama para wanita lainnya yang masih selamat kemudian melarikan diri ke dalam hutan.\n" +
                    "\n" +
                    "Setelah kematian Pang Nagroe, Cut Meutia masih terus melakukan perlawanan terhadap Belanda bersama sepasukan kecil pengikutnya. Mereka berusaha menyerang dan merampas pos-pos kolonial sepanjang perjalanan mereka ke Gayo melewati hutan belantara. Namun, pada pertempuran di Alue Kurieng tanggal 24 Oktober 1910 Cut Meutia akhirnya gugur akibat tembakan peluru tentara Belanda. Atas jasa-jasanya, pemerintah menganugerahi gelar Pahlawan Nasional pada Cut Meutia di tahun 1964.",
            "Sisingamangaraja XII (lahir di Bakara, 18 Februari 1845 – meninggal di Dairi, 17 Juni 1907 pada umur 62 tahun) adalah seorang raja di negeri Toba, Sumatera Utara, pejuang yang berperang melawan Belanda, kemudian diangkat oleh pemerintah Indonesia sebagai Pahlawan Nasional Indonesia sejak tanggal 9 November 1961 berdasarkan SK Presiden RI No 590/1961. Sebelumnya ia dimakamkan di Tarutung Tapanuli Utara, lalu dipindahkan ke Soposurung, Balige pada tahun 1953.\n" +
                    "\n" +
                    "Sisingamangaraja XII nama kecilnya adalah Patuan Bosar, yang kemudian digelari dengan Ompu Pulo Batu. Ia juga dikenal dengan Patuan Bosar Ompu Pulo Batu, naik tahta pada tahun 1876 menggantikan ayahnya Sisingamangaraja XI yang bernama Ompu Sohahuaon, selain itu ia juga disebut juga sebagai raja imam.Penobatan Sisingamangaraja XII sebagai maharaja di negeri Toba bersamaan dengan dimulainya open door policy (politik pintu terbuka) Belanda dalam mengamankan modal asing yang beroperasi di Hindia Belanda, dan yang tidak mau menandatangani Korte Verklaring (perjanjian pendek) di Sumatera terutama Kesultanan Aceh dan Toba, di mana kerajaan ini membuka hubungan dagang dengan negara-negara Eropa lainya.\n" +
                    "\n" +
                    "Di sisi lain Belanda sendiri berusaha untuk menanamkan monopolinya atas kerajaan tersebut. Politik yang berbeda ini mendorong situasi selanjutnya untuk melahirkan Perang Tapanuli yang berkepanjangan hingga puluhan tahun.Pada tahun 1877 para misionaris di Silindung dan Bahal Batu meminta bantuan kepada pemerintah kolonial Belanda dari ancaman diusir oleh Singamangaraja XII. Kemudian pemerintah Belanda dan para penginjil sepakat untuk tidak hanya menyerang markas Si Singamangaraja XII di Bakara tetapi sekaligus menaklukkan seluruh Toba.\n" +
                    "\n" +
                    "Pada tanggal 6 Februari 1878 pasukan Belanda sampai di Pearaja, tempat kediaman penginjil Ingwer Ludwig Nommensen.Kemudian beserta penginjil Nommensen dan Simoneit sebagai penerjemah pasukan Belanda terus menuju ke Bahal Batu untuk menyusun benteng pertahanan[butuh rujukan]. Namun kehadiran tentara kolonial ini telah memprovokasi Sisingamangaraja XII, yang kemudian mengumumkan pulas (perang) pada tanggal 16 Februari 1878 dan penyerangan ke pos Belanda di Bahal Batu mulai dilakukan.\n" +
                    "\n" +
                    "Pada tanggal 14 Maret 1878 datang Residen Boyle bersama tambahan pasukan yang dipimpin oleh Kolonel Engels sebanyak 250 orang tentara dari Sibolga. Pada tanggal 1 Mei 1878, Bangkara pusat pemerintahan Si Singamangaraja diserang pasukan kolonial dan pada 3 Mei 1878 seluruh Bangkara dapat ditaklukkan namun Singamangaraja XII beserta pengikutnya dapat menyelamatkan diri dan terpaksa keluar mengungsi. Sementara para raja yang tertinggal di Bakara dipaksa Belanda untuk bersumpah setia dan kawasan tersebut dinyatakan berada dalam kedaulatan pemerintah Hindia Belanda.Walaupun Bakara telah ditaklukkan, Singamangaraja XII terus melakukan perlawanan secara gerilya, namun sampai akhir Desember 1878 beberapa kawasan seperti Butar, Lobu Siregar, Naga Saribu, Huta Ginjang, Gurgur juga dapat ditaklukkan oleh pasukan kolonial Belanda.\n" +
                    "\n" +
                    "Di antara tahun 1883-1884, Singamangaraja XII berhasil melakukan konsolidasi pasukannya. Kemudian bersama pasukan bantuan dari Aceh, secara ofensif menyerang kedudukan Belanda antaranya Uluan dan Balige pada Mei 1883 serta Tangga Batu pada tahun 1884.",
            "Sri Susuhunan Pakubuwono VI merupakan salah satu raja yang pernah bertahta di Kasunanan Surakarta Hadiningrat. Sri Susuhunan Pakubuwono VI memiliki sebutan Sinuhun Bangun Tapa karena beliau sering melakukan meditasi atau tapa brata.Sri Susuhunan Pakubuwono VI lahir dengan nama asli Raden Mas Sapardan di Surakarta pada tanggal 26 April 1807. Dia merupakan keturunan dari Sri Susuhan Pakubuwana V dengan istrinya Raden Ayu Sosrokusumo yang memiliki darah keturunan dari Ki Juru Martani.Meskipun bukan anak dari Ratu, Pakubuwono VI dapat diangkat menjadi raja setelah ayahnya yang meninggal pada tahun 1923 memberikan wasiat agar Pakubuwono VI diangkat menjadi raja Kerajaan Surakarta.\n" +
                    "\n" +
                    "Pakubuwono VI pun resmi naik tahta pada tanggal 15 September 1823. Pada waktu Pakubuwono VI memerintah, baik Kerajaan Yogyakarta maupun Kerajaan Surakarta sedang menghadapi masa suram. Pengaruh Belanda di kedua kerajaan tersebut sudah sangat besar.Bahkan dalam pengangkatan raja, Belanda turut menentukan. Wilayah kerajaan semakin sempit. Banyak daerah yang diambil dan diperintah langsung oleh Belanda. Selain itu, dikeluarkan pula peraturan tata tertib yang sangat merendahkan martabat raja-raja.Para bangsawan diadu domba, sehingga dalam istana timbul golongan yang pro dan golongan yang anti Belanda. Sementara itu rakyat semakin sengsara. Akibatnya, baik di Surakarta maupun di Yogyakarta terjadi kegelisahan umum.\n" +
                    "\n" +
                    "Pada tahun 1825 meletus perang yang dipimpin oleh Diponegoro, seorang pangeran Yogyakarta. Perang itu dikenal dengan nama Perang Diponegoro (1825-1830). Pakubuwono VI sudah bersiap-siap menggabungkan diri dengan Diponegoro, namun tak dapat terlaksana sebab Panglima Tentara Hindia Belanda, Jenderal de Kock, dengan cepat tiba di Surakarta.Karena itu, ia terpaksa bersikap pasif, bahkan dipaksa mengirimkan pasukan untuk membantu Belanda memerangi Diponegoro. Setelah Perang Jawa berakhir, Belanda memberikan tekanan yang cukup berat terhadap Pakubuwono VI.Dia dipaksa menandatangani perjanjian yang berisi penyerahan beberapa daerah kepada Belanda. Dia menolak untuk menandatangani perjanjian tersebut dan membuat jengkel Belanda.Karena tekanan makin berat, pada tanggal 6 Juni 1830 Pakubuwono VI meninggalkan istana dan pergi ke Imogiri mengunjungi makam nenek moyangnya.Mengetahui hal ini, pemerintah Belanda justru menuduhnya sedang menyiapkan pemberontakan, lalu ditangkap dan dibuang ke Ambon. Pakubuwana VI meninggal dunia di Ambon pada tanggal 2 Juni 1849.\n" +
                    "\n" +
                    "Menurut laporan resmi Belanda, ia meninggal karena kecelakaan saat berpesiar di laut. Pada tahun 1957 jasad Pakubuwana VI dipindahkan dari Ambon ke Astana Imogiri, yaitu kompleks pemakaman keluarga raja keturunan Mataram.Sunan Pakubuwana VI sendiri telah ditetapkan pemerintah Republik Indonesia sebagai pahlawan nasional berdasarkan S.K. Presiden RI No. 294 Tahun 1964, tanggal 17 November 1964.Baru-barusan ini, pada saat makamnya digali, ditemukan bukti bahwa tengkorak Pakubuwana VI berlubang di bagian dahi. Menurut analisis Jend. TNI Pangeran Haryo Jatikusumo (putra Pakubuwana X), lubang tersebut seukuran peluru senapan Baker Riffle.Ditinjau dari letak lubang, Pakubuwana VI jelas bukan mati karena bunuh diri, apalagi kecelakaan saat berpesiar. Raja Surakarta yang anti penjajahan ini diperkirakan mati dibunuh dengan cara ditembak pada bagian dahi.",
            "Jenderal Soedirman ialah salah seorang Pahlawan Revolusi Nasional Indonesia. Dalam sejarah perjuangan Republik Indonesia, ia merupakan Panglima dan Jenderal RI yang pertama dan termuda. Pada usia yang masih cukup muda, yaitu 31 tahun, Soedirman telah menjadi seorang jenderal. Selain itu, ia juga dikenal sebagai pejuang yang gigih. Meskipun ia sedang menderita penyakit paru-paru parah, ia tetap berjuang dan bergerilya bersama para prajuritnya untuk melawan tentara Belanda pada Agresi Militer II. \n" +
                    "\n" +
                    "Soedirman lahir di Purbalingga, Jawa Tengah pada tanggal 24 Januari 1916. Ia berasal dari keluarga sederhana. Ayahnya seorang pekerja di pabrik gula Kalibagor Banyumas dan ibunya keturunan Wedana Rembang. Soedirman memperoleh pendidikan formal dari Sekolah Taman Siswa. Ia kemudian melanjutkan pendidikannya ke HIK (sekolah guru) Muhammadiyah, Solo tetapi tidak sampai tamat. Selama menempuh pendidikan di sana, ia pun turut serta dalam kegiatan organisasi Pramuka Hizbul Wathan. Setelah itu ia menjadi guru di sekolah HIS Muhammadiyah di Cilacap. Ia kemudian mengabdikan dirinya menjadi guru HIS Muhammadiyah, Cilacap dan pemandu di organisasi Pramuka Hizbul Wathan tersebut.\n" +
                    "\n" +
                    "Pada zaman penjajahan Jepang , Soedirman bergabung dengan tentara Pembela Tanah Air (Peta) di Bogor. Pasca Indonesia merdeka dari penjajahan Jepang, ia berhasil merebut senjata pasukan Jepang di Banyumas. Kemudian beliau diangkat menjadi Komandan Batalyon di Kroya setelah menyelesaikan pendidikannya. Ia lalu menjadi Panglima Divisi V/Banyumas sesudah TKR (Tentara Keamanan Rakyat) terbentuk, dan akhirnya terpilih menjadi Panglima Angkatan Perang Republik Indonesia (Panglima TNI). Perang Palagan Ambarawa melawan pasukan Inggris dan NICA Belanda dari bulan November sampai Desember 1945 adalah perang besar pertama yang ia pimpin. Karena ia berhasil memperoleh kemenangan pada pertempuran ini, Presiden Soekarno pun melantiknya sebagai Jenderal.\n" +
                    "\n" +
                    "Soedirman meninggal pada tanggal 29 Januari 1950 karena penyakit tuberkulosis parah yang ia derita. Jenazahnya dimakamkan di Taman Makam Pahlawan Kusuma Negara di Semaki, Yogyakarta. Pada tahun 1997 ia dianugerahi gelar sebagai Jenderal Besar Anumerta dengan bintang lima, pangkat yang hanya dimiliki oleh tiga jenderal di RI sampai sekarang. ",
            "Sutan Syahrir (Soetan Sjahrir) adalah Pahlawan nasional Indonesia yang lahir di Padang Panjang, Sumatera Barat, 5 Maret 1909 adalah seorang intelektual, perintis, dan revolusioner kemerdekaan Indonesia. Setelah Indonesia merdeka, ia menjadi politikus dan perdana menteri pertama Indonesia. Ia menjabat sebagai Perdana Menteri Indonesia dari 14 November 1945 hingga 20 Juni 1947. Ia juga mendirikan Partai Sosialis Indonesia pada tahun 1948. \n" +
                    "\n" +
                    "Syahrir lahir dari pasangan Mohammad Rasad gelar Maharaja Soetan bin Soetan Leman gelar Soetan Palindih dan Puti Siti Rabiah yang berasal dari Koto Gadang, Agam, Sumatera Barat. Ia pernah mengenyam sekolah dasar di Europeesche Lagere School (ELS) dan sekolah menengah Meer Uitgebreid Lager Onderwijs (MULO) terbaik di Medan. Pada 1926, ia masuk ke sekolah lanjutan atas Algemene Middelbare School (AMS) di bandung, di mana sekolah tersebut adalah sekolah termahal di Hindia Belanda pada saat itu. Dia juga bergabung dalam Himpunan Teater Mahasiswa Indonesia (Batovis) sebagai sutradara, penulis skenario, dan juga aktor. Dari hasil pementasan tersebut digunakan untuk membiayai sekolah yang ia dirikan, Tjahja Volksuniversiteit (Cahaya Universitas Rakyat). Setelah itu, ia melanjutkan pendidikannya ke negeri Belada di Fakultas Hukum, Universitas Amsterdam. Dan di sana ia mendalami sosialisme, secara sungguh-sungguh ia mempelajari teori-teori sosialisme, pada penghujung tahun 1931, Syahrir meninggalkan kampusnya untuk kembali ke tanah air dan terjun dalam pergerakan nasional. Ia kemudian bergabung dengan organisasi Partai Nasional Indonesia (PNI Baru), yang pada Juni 1932 diketuainya.\n" +
                    "\n" +
                    "Pada 26 Juni 1946 di Surakarta terjadi peristiwa penculikan terhadap dirinya oleh kelompok oposisi Persatuan Perjuangan yang tidak puas atas diplomasi yang dilakukannya. Kelompok tersebut menginginkan kedaulatan penuh (Merdeka 100%) yang dicetuskan oleh Tan Malaka. Sedangkan kabinet yang berkuasa pada saat itu hanya menuntut pengakuan kedaulatan atas Jawa dan Madura.Presiden Soekarno sangat marah atas aksi penculikan tersebut dan memerintahkan Polisi Surakarta menangkap para pimpinan kelompok tersebut. Setelah terjadinya penculikan tersebut, ia hanya bertugas sebagai Menteri Luar Negeri, tugas sebagai Perdana Menteri diambil alih oleh Presiden Soekarno. Selepas memimpin kabinet, ia diangkat menjadi penasehat Presiden Soekarno sekaligus Duta Besar Keliling. Ia mendirikan Partai Sosialis (PSI) pada tahun 1948.Syahrir meninggal di Zurich, Swiss, 9 April 1966 pada usia 57 tahun. Ia meninggal dalam pengasingan sebagai tawanan politik dan dimakamkan di TMP Kalibata, Jakarta.\n",
            "Lahir pada 21 April 1979, R. A Kartini sendiri dikenal luas sebagai tokoh emansipasi wanita di Indonesia. Putri dari Raden Mas Adipati Ario Sosroningrat ini kemudian menjalani masa sekolah hingga usia 12 tahun, usia saat ia mulai dipingit. R.A Kartini sendiri mengenyam pendidikannya di Europese Lagere School.Setelah dipingit pada usia 12 tahun, Karini tetap melanjutkan proses belajarnya di rumah, berlatih menulis dan membaca. Karena memiliki kemampuan bahasa Belanda yang baik, ia lantas terus belajar dengan berkirim surat dengan teman-temannya yang ada di Belanda.Dari aktivitas bekirim surat dengan sahabat penanya ini, selain mendapatkan ilmu dari dunia luar, Kartini juga  mendapatkan banyak buku dan koran Eropa, yang dikirimkan oleh teman-temannya.Kartini muda memiliki keinginan untuk memajukan perempuan Indonesia, yang pada masa tersebut hanya memiliki status sosial yang sangat rendah. Ia merintis keinginannya ini dengan mengajari anak-anak perempuan di sekitarnya untuk bisa menulis dan membaca.\n" +
                    "\n" +
                    "Pada 12 November 1903, Kartini menikah dengan Bupati Rembang kala itu, Raden Adipati Joyodiningrat. Suaminya mendukung dan memberikan kebebasan padanya, sehingga ia mampu mendirikan sekolah wanita di kompleks kantor Kabupaten Rembang.Sekolah ini terus dikembangkan hingga pada 1912, Sekolah Wanita oleh Yayasan Kartini resmi didirikan di Semarang. Menyusul setelahnya sekolah wanita di Surabaya, Yogyakarta, Malang, Madiun, hingga Cirebon.Kartini dan suaminya, kemudian dianugerahi seorang anak yang lahir pada tanggal 13 September 1904, yang diberi nama Soesalit Djojoadhiningrat. Malang, empat hari setelah kelahiran buah hatinya, Kartini meninggal dunia. Kala itu usia 25 tahun.Perjuangannya dalam mengangkat derajat Perempuan Indonesia kemudian mendapat dukungan dari rekan dekatnya, Mr. J.H. Abendanon, yang mengumpulkan surat-surat dari Kartini dan kemudian menjadikannya sebuah buku berjudul Habis Gelap Terbitlah Terang.",
            "Fatmawati, wanita asli pribumi ini lahir di Bengkulu pada tanggal 5 Februari 1923 dengan nama asli Fatimah. Nama Fatimah merupakan pemberian dari kedua orang tuanya. Fatmawati merupakan keturunan dari pasangan Hassan Din dan Siti Chadijah yang mana kedua orangtuanya adalah keturunan Puti Indrapura atau biasa disebut seorang keluarga raja dari kesultanan Indrapura, Pesisir Selatan, Sumatra Barat. Ayah Fatmawati juga terkenal sebagai salah satu tokoh Muhammadiyah di Bengkulu. Fatmawati dididik dan dibesarkan kedua orangtuanya di Bengkulu.Ketika beranjak dewasa, Fatmawati menikah dengan Presiden Indonesia Pertama Soekarno pada tanggal 01 Juni 1943, saat itu Fatmawati berusia 20 tahun. Dari pernikahan tersebut, secara otomatis Fatmawati menjadi Ibu Negara Indonesia pertama dari tahun 1945 hingga tahun 1967.\n" +
                    "\n" +
                    "Fatmawati merupakan istri yang ketiga dari Presiden Pertama Indonesia, Soekarno. Pasangan Pemimpin Negara Indonesia tersebut dikaruniai lima orang putra dan putri, di antaranya adalah Guntur Soekarnoputra, Megawati Soekarnoputri, Rachmawati Soekarnoputri, Sukmawati Soekarnoputri, dan yang terakhir Guruh Soekarnoputra.Ibu Negara Indonesia Pertama ini terkenal sebagai wanita yang berjasa dalam menjahit bendera Sang Saka Merah Putih yang dengan tegas dikibarkan pada upacara pertama Proklamasi Kemerdekaan Indonesia di Jakarta tepatnya pada tanggal 17 Agustus 1945.\n" +
                    "\n" +
                    "Fatmawati meninggal pada tanggal 14 Mei 1980 pada usia 57 tahun di Kuala Lumpur, Malaysia karena serangan jantung ketika dalam perjalanan pulang umroh dari Mekkah. Fatmawati dimakamkan di Karet Bivak, Jakarta. Saat ini nama Fatmawati dijadikan sebuah nama Rumah Sakit di Jakarta, nama Fatmawati Soekarno juga dijadikan sebuah nama Bandara Udara di Indonesia tepatnya di Bengkulu, kota kelahiran Fatmawati.",
            "Raden Dewi Sartika adalah putri pasangan raden Somanegara dan Raden Ayu Permas. Ayahnya adalah seorang patih di Bandung yang sangat Nasionalis. Ketika ayah dan ibunya ditangkap dan diasingkan ke ternate (Maluku), lalu dia dititipkan pada pamannya, Patih Aria yang tinggal di Cicalengka. Dewi lahir di Bandung, 4 Desember 1884, dia adalah tokoh perintis pendidikan untuk kaum perempuan. Diakui sebagai Pahlawan Nasional oleh Pemerintah Indonesia tahun 1966\n" +
                    "\n" +
                    "Dewi Sartika amat gigih dalam memperjuangkan nasib dan harkat kaum perempuan. Pada 16 Januari 1904, dia mendirikan sekolah istri atau sekolah untuk perempuan di bandung. Pada tahun 1910, sekolah istri berganti nama menjadi sakola kautamaan istri.  Sekolah Istri tersebut terus mendapat perhatian positif dari masyarakat. Murid- murid bertambah banyak, bahkan ruangan Kepatihan Bandung yang dipinjam sebelumnya juga tidak cukup lagi menampung murid-murid. Untuk mengatasinya, Sekolah Istri pun kemudian dipindahkan ke tempat yang lebih luas. Seiring perjalanan waktu, enam tahun sejak didirikan, pada tahun 1910, nama Sekolah Istri sedikit diperbarui menjadi Sekolah Keutamaan Istri. Perubahan bukan cuma pada nama saja, tapi mata pelajaran juga bertambah.\n" +
                    "\n" +
                    "Kemudian pada 1913, berdiri pula organisasi kautamaan istri di tasikmalaya. Organisasi ini menaungi sekolah-sekolah yang didirikan oleh dewi sartika. Pada tahun 1929, sakola kautamaan istri diubah namanya menjadi Sakolah Raden Dewi dan oleh pemerintah Hindia Belanda dibangunkan sebuah gedung baru yang besar dan lengkap.Dia berusaha keras mendidik anak-anak gadis agar kelak bisa menjadi ibu rumah tangga yang baik, bisa berdiri sendiri, luwes, dan terampil. Maka untuk itu, pelajaran yang berhubungan dengan pembinaan rumah tangga banyak diberikannya. Untuk menutupi biaya operasional sekolah, ia membanting tulang mencari dana. Semua jerih payahnya itu tidak dirasakannya jadi beban, tapi berganti menjadi kepuasan batin karena telah berhasil mendidik kaumnya. Salah satu yang menambah semangatnya adalah dorongan dari berbagai pihak terutama dari Raden Kanduruan Agah Suriawinata, suaminya, yang telah banyak membantunya mewujudkan perjuangannya, baik tenaga maupun pemikiran.\n" +
                    "\n" +
                    "Pada tahun 1947, akibat agresi militer Belanda, Dewi Sartika ikut mengungsi bersama-sama para pejuang yang terus malakukan perlawanan terhadap Belanda untuk mempertahankan kemerdekaan. Saat mengungsi inilah, tepatnya tanggal 11 september 1947, Dewi sartika yang sudah lanjut usia wafat di Cinean, Jawa Barat. Setelah keadaan aman, makamnya dipindahkan ke Bandung.",
            "Cut Meutia merupakan salah satu pejuang wanita dari Aceh yang telah diakui sebagai pahlawan nasional Indonesia. Sama halnya dengan para pejuang dari Tanah Rencong lainnya seperti Cut Nyak Dhien, Teuku Umar, Teuku Cik Di Tiro, dan tokoh pejuang Aceh lainnya, Cut Meutia dikenal sebagai sosok pemberani dan memiliki semangat juang yang tinggi serta tekad kuat untuk mengenyahkan para penjajah.\n" +
                    "\n" +
                    "Cut Meutia bertempur melawan Belanda bersama suaminya Teuku Muhammad atau lebih dikenal sebagai Teuku Tjik Tunong. Mereka bersama-sama melalui perjuangan yang panjang, namun pada akhirnya Teuku Tjik Tunong ditangkap oleh pihak Belanda pada bulan Maret tahun 1905. Teuku Tjik Tunong kemudian dijatuhi hukuman mati oleh Belanda di tepi pantai Lhokseumawe. Sebelum meninggal, ia berpesan pada sahabatnya Pang Nagroe agar mau menikahi istrinya dan merawat anaknya sepeninggal dirinya kelak.\n" +
                    "\n" +
                    "Sesuai pesan mendiang suaminya, Cut Meutia pun menikah dengan Pang Nagroe lalu bergabung bersama pasukan pimpinan Teuku Muda Gantoe. Dalam suatu pertempuran melawan Korps Marechausée di Paya Cicem, Pang Nagroe tewas dalam peperangan pada tanggal 26 September 1910 sedangkan Cut Meutia berhasil selamat. Ia bersama para wanita lainnya yang masih selamat kemudian melarikan diri ke dalam hutan.\n" +
                    "\n" +
                    "Setelah kematian Pang Nagroe, Cut Meutia masih terus melakukan perlawanan terhadap Belanda bersama sepasukan kecil pengikutnya. Mereka berusaha menyerang dan merampas pos-pos kolonial sepanjang perjalanan mereka ke Gayo melewati hutan belantara. Namun, pada pertempuran di Alue Kurieng tanggal 24 Oktober 1910 Cut Meutia akhirnya gugur akibat tembakan peluru tentara Belanda. Atas jasa-jasanya, pemerintah menganugerahi gelar Pahlawan Nasional pada Cut Meutia di tahun 1964.",
            "Letnan Jenderal TNI Anumerta Mas Tirtodarmo Haryono atau biasa dikenal sebagai MT Haryono adalah salah satu dari tujuh pahlawan revolusi Indonesia yang meninggal pada tragedi lubang buaya. Pada masa pendudukan Belanda di Indonesia, MT Haryono sempat memperoleh pendidikan di berbagai tempat.Yang pertama adalah di ELS, pendidikan setingkat sekolah dasar bentukan Belanda. MT Haryono juga sempat melanjutkan sekolah di HBS, pendidikan setingkat sekolah umum. Kemudian beralih ke masa pendudukan Jepang, MT Haryono sempat disekolahkan ke Ika Dai Gakko, sebuah sekolah kedokteran pada masa pendudukan Jepang, tetapi tidak sampai selesai.\n" +
                    "\n" +
                    "Ketika kemerdekaan RI dikumandangkan, MT Haryono sedang berada di Jakarta dan segera bergabung dengan para pemuda lain untuk mempertahankan Indonesia. Semangat perjuangan tersebut juga dilanjutkan dengan masuknya MT Haryono ke TKR (Tentara Keamanan Rakyat). Pada masa awal pengangkatannya, MT Haryono mendapat jabatan sebagai Mayor. Dengan prestasinya, MT Haryono pun akhirnya berkali-kali naik pangkat hingga mendapat jabatan Letnan Jenderal.\n" +
                    "\n" +
                    "Pada tragedy G30S PKI yang terjadi pada tanggal 30 September 1965, MT Haryono menjadi salah satu korban indsiden lubang buaya. Ia adalah salah satu korban yang ditemukan meninggal di lubang buaya. Para korban dari insiden G30S PKI tersebut kemudian dijuluki sebagai Pahlawan Revolusi. Selain MT Haryono, pahlawan revolusi lainnya yang turut menjadi korban adalah Jenderal TNI (Anumerta) Achmad Yani, Letjen. (Anumerta) Siswondo Parman, Letjen. (Anumerta) Suprapto, Mayjen. (Anumerta) Donald Isaac Pandjaitan, Mayjen. (Anumerta) Sutojo Siswomihardjo, Brigjen. (Anumerta) Katamso Darmokusumo (wafat di Yogyakarta), Kolonel Inf. (Anumerta) Sugiono (wafat di Yogyakarta), Kapten CZI (Anumerta) Pierre Tendean, dan Aipda (Anumerta) Karel Satsuit Tubun. Jenazah MT Haryono dimakamkan di TMP Kalibata, Jakarta.",
            " Jendral TNI (Anumerta) Ahmad Yani adalah salah satu Pahlawan Revolusi yaitu pahlawan yang gugur akibat adanya pemberontakan G 30 S/PKI.  Beliau dilahirkan di Purworejo pada tanggal 19 Juni 1922. Ketika SD, Beliau mengenyam pendidikan di HIS di daerah Bogor. Beliau menamatkannya pada tahun 1935. Lalu beliau meneruskan SMP nya di MULO kelas B Afd. Bogor hingga tahun 1938 yang kemudian diteruskan ke AMS bagian B Afd. Jakarta. Namun di sekolah lanjutan ini beliau tak bisa menamatkannya (hanya sampai kelas 2) karena Pemerintah Hindia Belanda mengumumkan sebuah milisi.Ahmad Yani yang belum tamat SMA kemudian tertarik pada dunia militer dan mendaftar ke Dinas Topografi Militer yang berada di daerah Malang, Jawa Timur yang kemudian dilanjutkan keintensifannya di daerah Bogor. Inilah awal karir Ahmad Yani di bidang militer. Beliau lulus dari pendidikan militer dengan berpangkat Sersan.Ketika Indonesia dijajah Jepang yakni pada tahun 1942, Ahmad Yani mendaftar untuk mengikuti pendidikan Heiho di Magelang, Jawa Tengah. Beliau lalu bergabung dengan PETA (Pembela Tanah Air) daerah cabang Bogor.\n" +
                    "\n" +
                    "Semasa perang kemerdekaan, Ahmad Yani juga banyak ikut andil. Jasa-jasanya adalah seperti beliau berhasil menyita senjata Jepang yang berada di Magelang. Ketika TKR lahir, beliau dijadikan Komandann TKR untuk wilayah Purworejo. Pada saat Belanda melancarkan Agresi Militernya ke indonesia yang pertama, Ahmad Yani bersama pasukan berhasil membendung serangan Belanda di daerah Pingit. Ketika Agresi yang ke dua, beliau juga diorbitkan dengan diangkat menjadi Komandan Wehrkreise II untuk menjaga daerah Kedu.Ketika pemberontakan DI/TII meletus, Ahmad Yani ditugasi untuk mengatasi pemberontakan itu di daerah Jawa Tengah. Bersama pasukan Benteng Raiders, akhirnya DI/TII berhasil dikalahkan. Setelah tugas itu selesai, beliau kembali ke Staf Angkatan Darat.Untuk lebih memperdalam ilmunya di bidang militer, pada 1955 Ahmad Yani diberangkatkan ke Amerika guna menempuh pendidikan di Command and General Staff College di Fort Leaven Worth, Kansas, USA selama sembilan bulan. Setahun kemudian beliau melanjutkann sekolah militer selama dua bulan di Inggris mengambil Spesial Warfre Course.Ketika terjadi pemberontakan PRRI di Sumatra Barat pada tahun 1958, Ahmad Yani yang saat itu berpangkat Kolonel didaulat menjadi Komandan Komando Operasi 17 Agustus yang kemudian memimpin penumpasan pemberontakan tersebut.Karena jasa dan prestasi beliau, pada tahun 1962, Ahmad Yani diangkat oleh Presiden Soekarno menjadi Menteri/Panglima Angkatan Darat.\n" +
                    "\n" +
                    "Dalam pandangan politik, Ahmad Yani tidak setuju dan selalu berseberangan dengan PKI. Ketika PKI berusaha untuk membentuk angkatan ke 5 yang terdiri dari buruh tani yang dipersenjatai, Ahmad Yani langsung menolaknya. Inilah yang menjadi alasan hingga beliau dimasukkan dalam target penculikan dan pembunuhan oleh PKI tahun 1965.Bersama dengan ke tujuh perwira Angkatan Darat lainnya, beliau diculik dan dibunuh lalu mayatnya dimasukkan kedalam sumur tua di daerah Lubang Buaya melalui operasi pemberontakan G30 S/PKI.Kronologinya, ketika dinihari tanggal 1 Oktober, Ahmad Yani ditembak di depan kamar tidurnya. Setelah dilakukan pencarian pada keesokan harinya, Jenazah Ahmad Yani kemudian dimakamkan secara hormat di Taman Makam Pahlawan Kalibata, Jakarta Selatan.Beliau bersama ketujuh perwira yang menjadi korban keganasan PKI kemudian dinamai sebagai Pahlawan Revolusi dan pangkatnya dinaikkan secara Anumerta yang awalya Letnan menjadi Jendral.",
            "Letnan Jenderal TNI Anumerta Siswondo Parman atau yang lebih dikenal dengan nama S. Parman merupakan salah satu pahlawan revolusi Indonesia dan tokoh militer Indonesia. S. Parman meninggal dunia setelah terbunuh pada peristiwa G30S PKI. S. Parman kemudian mendapatkan gelar Letnan Jenderal Anumerta. S. Parman adalah anak keenam dari sebelas bersaudara yang dilahirkan di Wonosobo, Jawa Tengah pada tanggal 4 Agustus 1918. Ayahnya bernama Kromodihardjo bekerja sebagai seorang pedagang. S. Parman memiliki seorang kakak laki-laki bernama Ir. Sakirman dimana nanti kakaknya ini akan menjadi petinggi di Politbiro CC PKI (semacam Dewan Syuro atau Dewan Penasihat Parpol sekarang).\n" +
                    "\n" +
                    "Meskipun Kromodihardjo hanyalah seorang pedagang di Pasar Wonosobo, dia selalu mengusahakan agar anak-anaknya bisa memperoleh pendidikan setinggi-tingginya. Parman menyelesaikan pendidikan di HIS (Hollandsch Inlandsche School) atau Sekolah Dasar Belanda di Wonosobo. Kemudian dia melanjutkan ke MULO (Meer Uitgebried Lager Onderwijs) atau Sekolah Menengah Pertama di Yogyakarta. Seharusnya dia setelah lulus, Parman melanjutkan ke AMS (Algemeene Middelbare School) yang setara dengan tingkat SMA namun karena ayahnya meninggal dunia pada tahun 1937 membuat Parman tidak bersekolah hampir dua tahun. parman kemudian membantu ibunya berdagang di Pasar Wonosobo. Setelah menemukan waktu yang tepat, Parman kembali melanjutkan sekolahnya di AMS. Sesuai dengan keinginan ayahnya, Parman kemudian masuk ke Sekolah Tinggi Kedokteran (STOVIA) di Jakarta.Dia tidak bisa menyelesaikan sekolah kedokterannya ini karena invasi Jepang pada tahun 1942. Suatu hari ketika Parman tengah berada di Wonosobo, ia bertemu polisi militer Jepang, Kenpetai yang mengatakan kalau mereka membutuhkan seseorang yang bisa berbahasa Inggris sebagai penerjemah. Mulai saat itu, Parman yang fasih berbahasa Inggris mengikuti Kenpetai hingga ke Yogyakarta. Meski membantu Jepang, rasa nasionalisme Parman tetap tinggi. Ia terus berhubungan dengan teman-temannya yang berjuang diam-diam untuk melawan Jepang.\n" +
                    "\n" +
                    "Setelah Indonesia merdeka, Parman memilih dunia militer sebagai tempat pengabdiannya pada negara. Selama Agresi Militer II, Parman ikut bergerilya di luar kota. Usai agresi, Parman sempat mengenyam pendidikan di Koninklijke Militaire Academie (semacam AKMIL) di Breda, Belanda. Tahun demi tahun, karir Parman terus menanjak, dia kemudian diangkat menjadi Asisten I Men Pangad bidang Intelijen dengan pangkat Brigadir Jenderal. Pada Agustus 1964, pangkatnya dinaikkan lagi menjadi Mayor Jenderal. Pada waktu memegang jabatan sebagai Asisten I bidang Intelijen, pengaruh PKI sudah meluas ke hampir seluruh bidang kenegaraan. Lawan utama PKI adalah Angkatan Darat. PKI menyebar opini publik bahwa AD berniat menggulingkan kepemimpinan Presiden Soekarno. Oleh karena itu, PKI mendesak Presiden membentuk Angkatan Kelima diamana anggotanya adalah buruh dan tani yang dipersenjatai.\n" +
                    "\n" +
                    "Saat itu, Parman menjadi salah satu pihak yang paling keras menolak rencana pembentukan Angkatan Kelima. Penolakan serta posisinya sebagai pejabat intelijen yang tahu banyak tentang PKI, menjadikannya sasaran utama PKI. Akhirnya pada dini hari tanggal 1 Oktober 1965, Parman diculik gerombolan G30S/PKI yang dipimpin Serma Satar dari Resimen Tjakrabirawa. Di Lubang Buaya, setelah disiksa dengan kejam Parman akhirnya menghembuskan napas terakhirnya. Jasadnya baru ditemukan tanggal 4 Oktober 1965 dan dimakamkan tanggal 5 Oktober 1965 di TMP Kalibata. Ironisnya, salah satu penggerak penculikan Parman tidak lain adalah kakak kandungnya sendiri, Ir. Sakirman yang merupakan petinggi di Politbiro CC PKI. ",
            "Letnan Jenderal TNI Anumerta R. Suprapto, seorang pahlawan revolusi Indonesia yang menjadi korban dalam G30SPKI pada tahun 1965 dan kini dimakamkan di Taman Makam Pahlawan Kalibata, Jakarta. Pria yang lahir pada tanggal 24 Agustus 1920 ini menyelesaikan pendidikan di sekolah MULO yang setara dengan SLTP dan AMS yang setara dengan SLTA sekarang pada tahun 1941.\n" +
                    "Suprapto kemudian memilih untuk masuk ke sekolah militer Belanda yang bernama Koninklijke Militaire Akademie di Bandung. Akan tetapi Suprapto tidak menyelesaikan pendidikan militernya dikarenakan oleh serbuan Jepang ke Indonesia. Ia bahkan sempat menjadi tahanan Jepang pada saat itu, namun Suprapto berhasil melarikan diri.\n" +
                    "\n" +
                    "Di masa awal kemerdekaan Indonesia, Suprapto bergabung dengan Tentara Keamanan Rakyat (TKR). Ia juga turut serta dalam pertempuran melawan Jepang di Cilacap dan berhasil melucuti senjata para tentara Jepang. Pria asal Purwokerto ini juga pernah diangkat menjadi ajudan dari Panglima Besar Sudirman pada tahun 1946. Pada bulan September 1949 ia lalu diangkat menjadi Kepala Staf Tentara dan Teritorial IV/Diponegoro di Semarang dan pada tahun 1951 berpindah ke Markas Besar TNI di Jakarta sebagai Staf Angkatan Darat.\n" +
                    "\n" +
                    "Pada tanggal 01 Oktober dini hari, Suprapto, yang saat itu tidak bisa tidur karena sakit gigi yang dideritanya, didatangi oleh sekawanan orang, yang mengaku sebagai pengawal kepresidenan (Cakrabirawa), yang mengatakan bahwa ia dipanggil oleh presiden Sukarno untuk menghadap. Suprapto kemudian dimasukkan ke dalam truk dan dibawa ke Lubang Buaya, daerah pinggiran kota Jakarta, bersama dengan 6 orang lainnya.Malam harinya, Jendral Suprapto dan keenam orang lainnya ditembak mati dan dilemparkan ke dalam sebuah sumur tua. Baru pada tanggal 5 Oktober, jenazah para korban pembunuhan tersebut bisa dikeluarkan dan dimakamkan di Taman Makam Pahlawan Kalibata. Di hari itu juga, Presiden Sukarno mengeluarkan Kepres no. 111/KOTI/1965, yang meresmikan Suprapto bersama korban Lubang Buaya yang lain sebagai Pahlawan Revolusi.",
            "Mayor Jenderal TNI Anumerta Donald Isaac Panjaitan adalah salah satu pahlawan revolusi terkenal di Indonesia. Meskipun ia meninggal dalam usia yang masih muda yakni 40 tahun, perjuangan beliau dalam mempertahankan tanah air sangat patut untuk diacungi jempol.\n" +
                    "\n" +
                    "Panjaitan adalah sosok pahlawan yang pernah mengenyam bangku SD hingga kuliah di Associated Command and General Staff College, Amerika Serikat. Selama masih di Indonesia, ia sempat menjadi anggota Gyugun di Pekanbaru, Riau dan membentuk Tentara Keamanan Rakyat (TKR) yang kemudian berubah menjadi TNI. Ia menduduki jabaran sebagai komandan batalyon di TKR yang kemudian menjadi KOmandan Pendidikan Divisi IX/Banteng di Bukittinggi pada tahun 1948. Setelah itu, ia menjadi Kepala Staff Umum IV (Supplay) Komandemen Tentara Sumatra.\n" +
                    "\n" +
                    "Pimpinan Perbekalan Perjuangan Pemerintah Darurat Republik Indonesia (PDRI) pun berhasil diraihnya ketika Agresi Militer Belanda ke II terjadi. Setelah Agresi Militer Belanda II berakhir, ia diangkat kembali menjadi Kepala Staf Operasi Tentara dan Teritorium (T&T) I Bukit Barisan di Medan yang selanjutnya di pindahkan ke palembang menjadi Kepala Staf T&T II/Sriwijaya.\n" +
                    "\n" +
                    "Setelah pulang menuntut ilmu di Amerika Serikat, Panjaitan membongkar rahasia PKI akan pengiriman senjata dari Republik Rakyat China yang dimasukkan ke dalam peti-peti bahan bangunan . Senjata-senjata tersebut diperkirakan akan digunakan oleh PKI untuk melancarkan aksi pemberontakan.Aksi Panjaitan atas pembongkaran rahasia PKI menyulut api kemarahan dari pihak PKI. Pada tanggal 1 Oktober 1965, sekelompok anggota Gerakan 30 September datang ke rumah Panjaitan. Ketika Panjaitan berusaha untuk melarikan diri, ia tertembak oleh anggota PKI dan meninggal. Mayatnya dibawa dan dibuang di Lubang BUaya. Pada tanggal 4 Oktober, mayat Panjaitan diambil dan dimakamkan secara layak di TMP Kalibata, Jakarta. Berkat keberaniannya membela negara, Panjaitan mendapatkan gelar Pahlawan Revolusi oleh pemerintah Indonesia.",
            "Sutoyo Siswomiharjo mengecap pendidikan HIS dan AMS di Semarang. Kemudian melanjutkan pendidikannya di Balai Pendidikan Pegawai Negeri di Jakarta. Sebelum menjadi tentara, Sutoyo bertugas sebagai Pegawai Menengah/III di Kabupaten Purworejo. Karirnya di bidang militer dimulai dengan menjabat sebagai Polisi Tentara saat perjuangan kemerdekaan 1945. Setelah itu karirnya terus menanjak sehingga pada tahun 1961 naik pangkat menjadi Kolonel dan menjabat sebagai IRKEHAD, lalu pada tahun 1964 dinaikkan pangkatnya menjadi Brigjen. \n" +
                    "\n" +
                    "Pak Toyo, panggilan akrab Sutoyo, dikenal masyarakat Indonesia saat dirinya menjadi korban G30S/PKI pada 1 Oktober 1965. Menjelang peristiwa tersebut Pak Toyo mengalami beberapa firasat yang tidak enak. Namun di tengah perasaan kurang enak itu, dia memerintahkan untuk membuat rencana peringatan Hari ABRI 5 Oktober 1965 secara cermat kepada ajudannya. Firasat itu ternyata terbukti tanggal 1 Oktober jam 04.00 Brigjen TNI Sutoyo diculik oleh pasukan yang dipimpin oleh Serma Surono dari Men Cakrabirawa dengan kekuatan 1  peleton. Dengan todongan bayonet, mereka menanyakan kepada pembantu rumah untuk menyerahkan kunci pintu yang menuju kamar tengah. Setelah pintu dibuka oleh Brigjen TNI Sutoyo, maka pratu Suyadi dan Praka Sumardi masuk ke dalam rumah, mereka mengatakan bahwa Brigjen TNI Sutoyo dipanggil oleh Presiden. Kedua orang itu membawa Brigjen TNI Sutoyo ke luar rumah sampai pintu pekarangan diserahkan pada Serda Sudibyo. Dengan diapit oleh Serda Sudibyo dan Pratu Sumardi, Brigjen TNI Sutoyo berjalan keluar pekarangan meninggalkan tempat untuk selanjutnya dibawa menuju Lubang Buaya. Pak Toyo gugur dianiaya di tempat tersebut, dan dianugerahi gelar Pahlawan Revolusi.",
            "Kapten Anumerta Pierre Andreas Tendean adalah seorang perwira militer Indonesia yang menjadi salah satu korban peristiwa Gerakan 30 September pada tahun 1965. Mengawali karier militer dengan menjadi intelijen dan kemudian ditunjuk sebagai ajudan Jenderal Abdul Haris Nasution dengan pangkat letnan satu, ia dipromosikan menjadi kapten anumerta setelah kematiannya. Tendean dimakamkan di Taman Makam Pahlawan Kalibata dan bersama enam perwira korban G30S lainnya, ia ditetapkan sebagai Pahlawan Revolusi Indonesia pada tanggal 5 Oktober 1965.\n" +
                    "\n" +
                    "Pierre Andreas Tendean terlahir pada tanggal 21 Februari 1939 di Batavia (kini Jakarta), Hindia Belanda dari pasangan Dr. A.L Tendean, seorang dokter yang berdarah Minahasa, dan Cornet M.E, serang wanita Indo yang berdarah Perancis. Pierre adalah anak kedua dari tiga bersaudara; kakak dan adiknya masing-masing bernama Mitze Farre dan Rooswidiati. Tendean mengenyam sekolah dasar di Magelang, lalu melanjutkan SMP dan SMA di Semarang tempat ayahnya bertugas. Sejak kecil, ia sangat ingin menjadi tentara dan masuk akademi militer, namun orang tuanya ingin ia menjadi seorang dokter seperti ayahnya atau seorang insinyur. Karena tekadnya yang kuat, ia pun berhasil bergabung dengan Akademi Teknik Angkatan Darat (ATEKAD) di Bandung pada tahun 1958.\n" +
                    "\n" +
                    "Pada tahun 1962 Tandean lulus dari akademi militer dengan pangkat letnan dua, dan menjadi Komandan Pleton Batalyon Zeni Tempur 2 Kodam II/Bukit Barisan di Medan. Setahun kemudian, ia mengikuti pendidikan di sekolah intelijen di Bogor. Setamat dari sana, ia ditugaskan di Dinas Pusat Intelijen Angkatan Darat (DIPIAD) untuk menjadi mata-mata ke Malaysia sehubungan dengan konfrontasi antara Indonesia dengan Malaysia; ia bertugas memimpin sekelompok relawan di beberapa daerah untuk menyusup ke Malaysia. Pada tanggal 15 April 1965, Tendean dipromosikan menjadi letnan satu, dan ditugaskan sebagai ajudan Jenderal Abdul Haris Nasution.\n" +
                    "\n" +
                    "Pada pagi tanggal 1 Oktober 1965, pasukan Gerakan 30 September (G30S) mendatangi rumah Nasution dengan tujuan untuk menculiknya. Tendean yang sedang tidur di ruang belakang rumah Jenderal Nasution terbangun karena suara tembakan dan ribut-ribut dan segera berlari ke bagian depan rumah. Ia ditangkap oleh gerombolan G30S yang mengira dirinya sebagai Nasution karena kondisi rumah yang gelap. Nasution sendiri berhasil melarikan diri dengan melompati pagar. Tendean lalu di bawa ke sebuah rumah di daerah Lubang Buaya bersama enam perwira tinggi lainnya. Ia ditembak mati dan mayatnya dibuang ke sebuah sumur tua bersama enam jasad perwira lainnya.Bersama keenam perwira lainnya Tendean dimakamkan di Taman Makam Pahlawan Kalibata, Jakarta. Untuk menghargai jasa-jasanya, Tendean dianugerahi gelar Pahlawan Revolusi Indonesia pada tanggal 5 Oktober 1965 berdasarkan Surat Keputusan Presiden RI No. 111/KOTI/Tahun 1965.",

    };
}
